version: '3.8'

services:
  # FastAPI application
  api:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://energyexe:password@db:5432/energyexe_db
      - REDIS_URL=redis://redis:6379
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
      - poetry-cache:/opt/poetry-cache
    depends_on:
      - db
      - redis
    networks:
      - energyexe-network

  # PostgreSQL database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=energyexe
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=energyexe_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - energyexe-network

  # Redis cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - energyexe-network

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@energyexe.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - energyexe-network

volumes:
  postgres_data:
  redis_data:
  poetry-cache:

networks:
  energyexe-network:
    driver: bridge 