version: '3.8'

services:
  mcp-postgres:
    image: node:18-alpine
    container_name: energyexe-mcp-postgres
    working_dir: /app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: >
      sh -c "
        npm install -g @modelcontextprotocol/server-postgres &&
        npx @modelcontextprotocol/server-postgres
      "
    ports:
      - "3000:3000"  # MCP server port
    networks:
      - energyexe-network
    restart: unless-stopped

  mcp-filesystem:
    image: node:18-alpine
    container_name: energyexe-mcp-filesystem
    working_dir: /app
    volumes:
      - .:/project:ro  # Mount project as read-only
    command: >
      sh -c "
        npm install -g @modelcontextprotocol/server-filesystem &&
        npx @modelcontextprotocol/server-filesystem /project
      "
    ports:
      - "3001:3000"  # MCP server port
    networks:
      - energyexe-network
    restart: unless-stopped

networks:
  energyexe-network:
    external: true