"""Endpoint tests for POST /api/v1/opportunities/detect (#114).

The detection engine reads JSONB tables that the in-memory SQLite test DB does
not have, so these tests NEVER run real detection. Instead they:

  * override ``get_current_active_user`` so the protected endpoint authenticates,
  * override ``get_db`` with a fake async session (no ``import_job_executions``
    table needed in SQLite),
  * patch ``OpportunityDetectionService`` (sync path) and the background runner
    (fleet-wide path) and assert what was scheduled / called with which kwargs.

This verifies the async-vs-sync branch + the ``schema_codes`` pass-through
WITHOUT requiring a live Postgres.
"""

from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from app.api.v1.endpoints import opportunities as opp_endpoint
from app.core.deps import get_current_active_user, get_db
from app.models.user import User


class _FakeSession:
    """Minimal async-session stand-in for the fleet-wide branch.

    The fleet-wide path does ``db.add(job)`` / ``await db.commit()`` /
    ``await db.refresh(job)`` on the request session. SQLite in the test DB has
    no ``import_job_executions`` table, so we fake it: ``add`` stamps a fake id,
    ``commit`` / ``refresh`` are no-ops, ``refresh`` keeps the stamped id.
    """

    def __init__(self, job_id: int = 4242):
        self._job_id = job_id
        self.added = []

    def add(self, obj):
        # Stamp an id as if the DB autogenerated one on flush/commit.
        if getattr(obj, "id", None) is None:
            obj.id = self._job_id
        self.added.append(obj)

    async def commit(self):
        return None

    async def refresh(self, obj):
        if getattr(obj, "id", None) is None:
            obj.id = self._job_id
        return None


@pytest.fixture
def fake_user():
    user = User(
        id=7,
        email="detect@example.com",
        username="detector",
        hashed_password="x",
        is_active=True,
    )
    return user


@pytest.fixture
def detect_client(client, fake_user):
    """``client`` with auth + DB overridden for the /detect endpoint."""
    app = client.app
    fake_db = _FakeSession()

    async def _override_user():
        return fake_user

    async def _override_db():
        yield fake_db

    app.dependency_overrides[get_current_active_user] = _override_user
    app.dependency_overrides[get_db] = _override_db

    yield client, fake_db

    app.dependency_overrides.pop(get_current_active_user, None)
    # Restore the conftest get_db override is handled by the client fixture teardown.


def test_detect_returns_job_id_and_runs_in_background(detect_client):
    """No windfarm_ids → 200/202 with a job_id; detection scheduled async."""
    client, _ = detect_client

    with patch.object(opp_endpoint, "_run_detection_in_background", new=AsyncMock()) as bg_mock:
        resp = client.post("/api/v1/opportunities/detect", json={})

    assert resp.status_code in (200, 202), resp.text
    body = resp.json()
    assert body["job_id"] == 4242
    assert body["mode"] == "background"
    assert body["status"] == "scheduled"

    # The background task was registered (FastAPI runs queued BackgroundTasks
    # after the response on the TestClient, so the runner is actually invoked).
    bg_mock.assert_awaited_once()
    kwargs = bg_mock.await_args.kwargs
    assert kwargs["job_id"] == 4242
    assert kwargs["period_months"] == 24
    assert kwargs["schema_codes"] is None


def test_detect_accepts_schema_codes_filter(detect_client):
    """schema_codes is parsed to SchemaCode members and threaded to the run."""
    from app.models.opportunity import SchemaCode

    client, _ = detect_client

    with patch.object(opp_endpoint, "_run_detection_in_background", new=AsyncMock()) as bg_mock:
        resp = client.post(
            "/api/v1/opportunities/detect",
            json={"schema_codes": ["OPS_01", "MKT_01"]},
        )

    assert resp.status_code in (200, 202), resp.text
    bg_mock.assert_awaited_once()
    passed = bg_mock.await_args.kwargs["schema_codes"]
    assert passed == [SchemaCode.OPS_01, SchemaCode.MKT_01]


def test_detect_windfarm_ids_sync_path(detect_client):
    """windfarm_ids supplied → synchronous run, inline results, no background job."""
    client, _ = detect_client

    inline_result = {
        "job_id": 99,
        "windfarms_scanned": 1,
        "opportunities_created": 3,
    }

    fake_service = MagicMock()
    fake_service.run_detection_job = AsyncMock(return_value=inline_result)

    with patch(
        "app.services.opportunity_detection_service.OpportunityDetectionService",
        return_value=fake_service,
    ), patch.object(opp_endpoint, "_run_detection_in_background", new=AsyncMock()) as bg_mock:
        resp = client.post(
            "/api/v1/opportunities/detect",
            json={"windfarm_ids": [1]},
        )

    assert resp.status_code == 200, resp.text
    body = resp.json()
    # Inline summary returned directly (NOT a DetectionTriggerResponse).
    assert body == inline_result
    assert "mode" not in body

    # No background job scheduled on the sync path.
    bg_mock.assert_not_awaited()

    # Service called synchronously with the scoped windfarm_ids.
    fake_service.run_detection_job.assert_awaited_once()
    call_kwargs = fake_service.run_detection_job.await_args.kwargs
    assert call_kwargs["windfarm_ids"] == [1]
    assert call_kwargs["schema_codes"] is None


def test_detect_sync_path_threads_schema_codes(detect_client):
    """windfarm_ids + schema_codes → sync run gets the parsed SchemaCode filter."""
    from app.models.opportunity import SchemaCode

    client, _ = detect_client

    fake_service = MagicMock()
    fake_service.run_detection_job = AsyncMock(return_value={"job_id": 1})

    with patch(
        "app.services.opportunity_detection_service.OpportunityDetectionService",
        return_value=fake_service,
    ):
        resp = client.post(
            "/api/v1/opportunities/detect",
            json={"windfarm_ids": [5], "schema_codes": ["FIN_01"]},
        )

    assert resp.status_code == 200, resp.text
    call_kwargs = fake_service.run_detection_job.await_args.kwargs
    assert call_kwargs["windfarm_ids"] == [5]
    assert call_kwargs["schema_codes"] == [SchemaCode.FIN_01]


def test_detect_rejects_unknown_schema_code(detect_client):
    """Unknown schema_code → 422, no run scheduled."""
    client, _ = detect_client

    with patch.object(opp_endpoint, "_run_detection_in_background", new=AsyncMock()) as bg_mock:
        resp = client.post(
            "/api/v1/opportunities/detect",
            json={"schema_codes": ["NOPE_99"]},
        )

    assert resp.status_code == 422, resp.text
    bg_mock.assert_not_awaited()
