"""Pydantic schemas package."""

from .control_area import ControlArea, ControlAreaCreate, ControlAreaUpdate
from .country import Country, CountryCreate, CountryInDB, CountryUpdate
from .data_anomaly import (
    DataAnomalyBase,
    DataAnomalyCreate,
    DataAnomalyUpdate,
    DataAnomalyStatusUpdate,
    DataAnomalyResponse,
    DataAnomalyDetectionResult,
    AnomalyDetectionRequest,
    AnomalyDetectionResponse,
    ReaggregationRequest,
    ReaggregationResponse,
    AnomalyListFilters,
    AnomalyListResponse,
)
from .generation_unit import (
    GenerationUnitCreate,
    GenerationUnitResponse,
    GenerationUnitSearchParams,
    GenerationUnitUpdate,
)
from .market_balance_area import MarketBalanceArea, MarketBalanceAreaCreate, MarketBalanceAreaUpdate
from .state import State, StateCreate, StateInDB, StateUpdate, StateWithCountry
from .invitation import (
    BulkInvitationCreate,
    BulkInvitationResult,
    InvitationAccept,
    InvitationCreate,
    InvitationResponse,
    InvitationValidation,
)
from .user import (
    ClientRegister,
    EmailVerification,
    ForgotPassword,
    PendingUserResponse,
    ResendVerification,
    ResetPassword,
    Token,
    TokenData,
    UserApproval,
    UserCreate,
    UserFeatureResponse,
    UserFeatureUpdate,
    UserLogin,
    UserResponse,
    UserResponseExtended,
    UserUpdate,
)
from .portfolio import (
    PortfolioCreate,
    PortfolioUpdate,
    PortfolioResponse,
    PortfolioWithItems,
    PortfolioItemCreate,
    PortfolioItemResponse,
    FavoriteCreate,
    FavoriteResponse,
    FavoriteListResponse,
    PortfolioSummary,
    PortfolioPerformance,
    PortfolioTypeEnum,
)
from .alert import (
    AlertRuleCreate,
    AlertRuleUpdate,
    AlertRuleResponse,
    AlertRuleListResponse,
    AlertTriggerResponse,
    AlertTriggerListResponse,
    AlertTriggerStatusUpdate,
    NotificationResponse,
    NotificationListResponse,
    NotificationMarkRead,
    NotificationMarkAllRead,
    NotificationPreferenceBase,
    NotificationPreferenceUpdate,
    NotificationPreferenceResponse,
    AlertsSummary,
    AlertsOverview,
    AlertMetricEnum,
    AlertConditionEnum,
    AlertScopeEnum,
    AlertSeverityEnum,
    NotificationChannelEnum,
    AlertTriggerStatusEnum,
    NotificationStatusEnum,
)

__all__ = [
    # User schemas
    "UserResponse",
    "UserResponseExtended",
    "UserCreate",
    "UserUpdate",
    "UserLogin",
    "Token",
    "TokenData",
    "ClientRegister",
    "EmailVerification",
    "ResendVerification",
    "ForgotPassword",
    "ResetPassword",
    "UserApproval",
    "UserFeatureUpdate",
    "UserFeatureResponse",
    "PendingUserResponse",
    # Invitation schemas
    "InvitationCreate",
    "BulkInvitationCreate",
    "InvitationAccept",
    "InvitationResponse",
    "InvitationValidation",
    "BulkInvitationResult",
    # Other schemas
    "Country",
    "CountryCreate",
    "CountryUpdate",
    "CountryInDB",
    "State",
    "StateCreate",
    "StateUpdate",
    "StateInDB",
    "StateWithCountry",
    "ControlArea",
    "ControlAreaCreate",
    "ControlAreaUpdate",
    "MarketBalanceArea",
    "MarketBalanceAreaCreate",
    "MarketBalanceAreaUpdate",
    "GenerationUnitCreate",
    "GenerationUnitUpdate",
    "GenerationUnitResponse",
    "GenerationUnitSearchParams",
    "DataAnomalyBase",
    "DataAnomalyCreate",
    "DataAnomalyUpdate",
    "DataAnomalyStatusUpdate",
    "DataAnomalyResponse",
    "DataAnomalyDetectionResult",
    "AnomalyDetectionRequest",
    "AnomalyDetectionResponse",
    "ReaggregationRequest",
    "ReaggregationResponse",
    "AnomalyListFilters",
    "AnomalyListResponse",
    # Portfolio schemas
    "PortfolioCreate",
    "PortfolioUpdate",
    "PortfolioResponse",
    "PortfolioWithItems",
    "PortfolioItemCreate",
    "PortfolioItemResponse",
    "FavoriteCreate",
    "FavoriteResponse",
    "FavoriteListResponse",
    "PortfolioSummary",
    "PortfolioPerformance",
    "PortfolioTypeEnum",
    # Alert schemas
    "AlertRuleCreate",
    "AlertRuleUpdate",
    "AlertRuleResponse",
    "AlertRuleListResponse",
    "AlertTriggerResponse",
    "AlertTriggerListResponse",
    "AlertTriggerStatusUpdate",
    "NotificationResponse",
    "NotificationListResponse",
    "NotificationMarkRead",
    "NotificationMarkAllRead",
    "NotificationPreferenceBase",
    "NotificationPreferenceUpdate",
    "NotificationPreferenceResponse",
    "AlertsSummary",
    "AlertsOverview",
    "AlertMetricEnum",
    "AlertConditionEnum",
    "AlertScopeEnum",
    "AlertSeverityEnum",
    "NotificationChannelEnum",
    "AlertTriggerStatusEnum",
    "NotificationStatusEnum",
]

# Resolve forward references
ControlArea.model_rebuild()
MarketBalanceArea.model_rebuild()
