"""add country_id to market_balance_areas

Revision ID: 08dd38656051
Revises: aa90cb1f965b
Create Date: 2025-07-21 01:08:49.230391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08dd38656051'
down_revision = 'aa90cb1f965b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_balance_areas', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_market_balance_areas_country_id'), 'market_balance_areas', ['country_id'], unique=False)
    op.create_foreign_key(None, 'market_balance_areas', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'market_balance_areas', type_='foreignkey')
    op.drop_index(op.f('ix_market_balance_areas_country_id'), table_name='market_balance_areas')
    op.drop_column('market_balance_areas', 'country_id')
    # ### end Alembic commands ### 