"""Add ENTSOE data storage tables

Revision ID: 16ef6dbd8674
Revises: remove_all_entsoe_historical
Create Date: 2025-08-14 16:34:50.545860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ef6dbd8674'
down_revision = 'remove_all_entsoe_historical'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entsoe_area_metadata',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('entsoe_generation_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('area_code', sa.String(length=10), nullable=False),
    sa.Column('production_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fetch_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'area_code', 'production_type', name='uq_entsoe_data_point')
    )
    op.create_index('idx_entsoe_created_at', 'entsoe_generation_data', ['created_at'], unique=False)
    op.create_index('idx_entsoe_fetch_id', 'entsoe_generation_data', ['fetch_id'], unique=False)
    op.create_index('idx_entsoe_timestamp_area_production', 'entsoe_generation_data', ['timestamp', 'area_code', 'production_type'], unique=False)
    op.create_table('entsoe_fetch_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('area_codes', sa.JSON(), nullable=False),
    sa.Column('production_types', sa.JSON(), nullable=False),
    sa.Column('fetch_status', sa.String(length=20), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('turbine_units_windfarm_id_fkey'), 'turbine_units', type_='foreignkey')
    op.create_foreign_key(None, 'turbine_units', 'windfarms', ['windfarm_id'], ['id'])
    op.drop_constraint(op.f('windfarm_owners_windfarm_id_fkey'), 'windfarm_owners', type_='foreignkey')
    op.create_foreign_key(None, 'windfarm_owners', 'windfarms', ['windfarm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'windfarm_owners', type_='foreignkey')
    op.create_foreign_key(op.f('windfarm_owners_windfarm_id_fkey'), 'windfarm_owners', 'windfarms', ['windfarm_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'turbine_units', type_='foreignkey')
    op.create_foreign_key(op.f('turbine_units_windfarm_id_fkey'), 'turbine_units', 'windfarms', ['windfarm_id'], ['id'], ondelete='CASCADE')
    op.drop_table('entsoe_fetch_history')
    op.drop_index('idx_entsoe_timestamp_area_production', table_name='entsoe_generation_data')
    op.drop_index('idx_entsoe_fetch_id', table_name='entsoe_generation_data')
    op.drop_index('idx_entsoe_created_at', table_name='entsoe_generation_data')
    op.drop_table('entsoe_generation_data')
    op.drop_table('entsoe_area_metadata')
    # ### end Alembic commands ### 