"""Add status field to generation_units

Revision ID: 175820ad757b
Revises: cdf860f8f78d
Create Date: 2025-09-05 17:04:24.398002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175820ad757b'
down_revision = 'cdf860f8f78d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_units', sa.Column('status', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_units', 'status')
    # ### end Alembic commands ### 