"""change_windfarm_nameplate_capacity_to_float

Revision ID: 18e12df6700a
Revises: f6efd3b5e60b
Create Date: 2025-08-02 21:56:22.728210

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '18e12df6700a'
down_revision = 'f6efd3b5e60b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('windfarms', 'nameplate_capacity_mw',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('windfarms', 'nameplate_capacity_mw',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ### 