"""Add windfarm owners many-to-many relationship with ownership percentage

Revision ID: 1fb7fa584433
Revises: f8e3b9a87c42
Create Date: 2025-07-25 01:34:06.323855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb7fa584433'
down_revision = 'f8e3b9a87c42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('windfarm_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('windfarm_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('ownership_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['windfarm_id'], ['windfarms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_windfarm_owners_id'), 'windfarm_owners', ['id'], unique=False)
    op.drop_constraint(op.f('windfarms_owner_id_fkey'), 'windfarms', type_='foreignkey')
    op.drop_column('windfarms', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('windfarms', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('windfarms_owner_id_fkey'), 'windfarms', 'owners', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_windfarm_owners_id'), table_name='windfarm_owners')
    op.drop_table('windfarm_owners')
    # ### end Alembic commands ### 