"""fix EIA and Taipower generation_unit_id data type

Revision ID: 27b4f666e96b
Revises: 378408c337ba
Create Date: 2025-08-17 21:05:25.875402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b4f666e96b'
down_revision = '378408c337ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 