"""add generation_units table

Revision ID: 2cee37de516d
Revises: 1fb7fa584433
Create Date: 2025-07-30 02:06:06.219389

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2cee37de516d"
down_revision = "1fb7fa584433"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generation_units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("fuel_type", sa.String(length=100), nullable=False),
        sa.Column("technology_type", sa.String(length=100), nullable=True),
        sa.Column("capacity_mw", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("windfarm_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_generation_units_code"), "generation_units", ["code"], unique=True)
    op.create_index(op.f("ix_generation_units_id"), "generation_units", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generation_units_id"), table_name="generation_units")
    op.drop_index(op.f("ix_generation_units_code"), table_name="generation_units")
    op.drop_table("generation_units")
    # ### end Alembic commands ###
