"""add EIA and Taipower generation data tables

Revision ID: 378408c337ba
Revises: 1569b67611e3
Create Date: 2025-08-17 20:47:51.464947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378408c337ba'
down_revision = '1569b67611e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('elexon_generation_data_unique'), 'elexon_generation_data', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('elexon_generation_data_unique'), 'elexon_generation_data', ['timestamp', 'bm_unit', 'settlement_period'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ### 