"""add energy tables

Revision ID: 3ea9ffb688a9
Revises: 85885ad21794
Create Date: 2025-07-20 21:28:10.562981

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "3ea9ffb688a9"
down_revision = "85885ad21794"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create owners table
    op.create_table(
        "owners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(op.f("ix_owners_code"), "owners", ["code"], unique=False)
    op.create_index(op.f("ix_owners_id"), "owners", ["id"], unique=False)

    # Create projects table
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("fuel_type", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(op.f("ix_projects_code"), "projects", ["code"], unique=False)
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)

    # Create turbine_models table
    op.create_table(
        "turbine_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=False),
        sa.Column("supplier", sa.String(length=50), nullable=False),
        sa.Column("original_supplier", sa.String(length=50), nullable=False),
        sa.Column("rated_power_kw", sa.Integer(), nullable=True),
        sa.Column("rotor_diameter_m", sa.DECIMAL(precision=6, scale=2), nullable=True),
        sa.Column("cut_in_wind_speed_ms", sa.DECIMAL(precision=4, scale=2), nullable=True),
        sa.Column("cut_out_wind_speed_ms", sa.DECIMAL(precision=4, scale=2), nullable=True),
        sa.Column("rated_wind_speed_ms", sa.DECIMAL(precision=4, scale=2), nullable=True),
        sa.Column("blade_length_m", sa.DECIMAL(precision=6, scale=2), nullable=True),
        sa.Column("generator_type", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model"),
    )
    op.create_index(op.f("ix_turbine_models_id"), "turbine_models", ["id"], unique=False)
    op.create_index(op.f("ix_turbine_models_model"), "turbine_models", ["model"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop turbine_models table
    op.drop_index(op.f("ix_turbine_models_model"), table_name="turbine_models")
    op.drop_index(op.f("ix_turbine_models_id"), table_name="turbine_models")
    op.drop_table("turbine_models")

    # Drop projects table
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_code"), table_name="projects")
    op.drop_table("projects")

    # Drop owners table
    op.drop_index(op.f("ix_owners_id"), table_name="owners")
    op.drop_index(op.f("ix_owners_code"), table_name="owners")
    op.drop_table("owners")
    # ### end Alembic commands ###
