"""Add bidzone_type field

Revision ID: 4aeb61709380
Revises: 65d443aec146
Create Date: 2025-07-21 00:21:48.703910

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4aeb61709380"
down_revision = "65d443aec146"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bidzones", sa.Column("bidzone_type", sa.String(length=50), nullable=True))
    op.drop_constraint(op.f("bidzones_code_key"), "bidzones", type_="unique")
    op.drop_index(op.f("ix_bidzones_code"), table_name="bidzones")
    op.create_index(op.f("ix_bidzones_code"), "bidzones", ["code"], unique=True)
    op.drop_constraint(op.f("control_areas_code_key"), "control_areas", type_="unique")
    op.drop_index(op.f("ix_control_areas_code"), table_name="control_areas")
    op.create_index(op.f("ix_control_areas_code"), "control_areas", ["code"], unique=True)
    op.drop_constraint(
        op.f("market_balance_areas_code_key"), "market_balance_areas", type_="unique"
    )
    op.drop_index(op.f("ix_market_balance_areas_code"), table_name="market_balance_areas")
    op.create_index(
        op.f("ix_market_balance_areas_code"), "market_balance_areas", ["code"], unique=True
    )
    op.drop_constraint(op.f("regions_code_key"), "regions", type_="unique")
    op.drop_index(op.f("ix_regions_code"), table_name="regions")
    op.create_index(op.f("ix_regions_code"), "regions", ["code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_regions_code"), table_name="regions")
    op.create_index(op.f("ix_regions_code"), "regions", ["code"], unique=False)
    op.create_unique_constraint(
        op.f("regions_code_key"), "regions", ["code"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_market_balance_areas_code"), table_name="market_balance_areas")
    op.create_index(
        op.f("ix_market_balance_areas_code"), "market_balance_areas", ["code"], unique=False
    )
    op.create_unique_constraint(
        op.f("market_balance_areas_code_key"),
        "market_balance_areas",
        ["code"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_control_areas_code"), table_name="control_areas")
    op.create_index(op.f("ix_control_areas_code"), "control_areas", ["code"], unique=False)
    op.create_unique_constraint(
        op.f("control_areas_code_key"),
        "control_areas",
        ["code"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_bidzones_code"), table_name="bidzones")
    op.create_index(op.f("ix_bidzones_code"), "bidzones", ["code"], unique=False)
    op.create_unique_constraint(
        op.f("bidzones_code_key"), "bidzones", ["code"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("bidzones", "bidzone_type")
    # ### end Alembic commands ###
