"""Add state table

Revision ID: 4fc39b4c04bd
Revises: 409827e82cb3
Create Date: 2025-07-20 20:26:30.063073

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4fc39b4c04bd"
down_revision = "409827e82cb3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("polygon_wkt", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_states_code"), "states", ["code"], unique=True)
    op.create_index(op.f("ix_states_id"), "states", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_states_id"), table_name="states")
    op.drop_index(op.f("ix_states_code"), table_name="states")
    op.drop_table("states")
    # ### end Alembic commands ###
