"""add geography tables

Revision ID: 85885ad21794
Revises: 4fc39b4c04bd
Create Date: 2025-07-20 20:52:14.600461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85885ad21794'
down_revision = '4fc39b4c04bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create regions table
    op.create_table('regions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('location_type', sa.String(length=255), nullable=False),
        sa.Column('lat', sa.Float(), nullable=True),
        sa.Column('lng', sa.Float(), nullable=True),
        sa.Column('polygon_wkt', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_regions_code'), 'regions', ['code'], unique=False)
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    
    # Create bidzones table
    op.create_table('bidzones',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('lat', sa.Float(), nullable=True),
        sa.Column('lng', sa.Float(), nullable=True),
        sa.Column('polygon_wkt', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_bidzones_code'), 'bidzones', ['code'], unique=False)
    op.create_index(op.f('ix_bidzones_id'), 'bidzones', ['id'], unique=False)
    
    # Create market_balance_areas table
    op.create_table('market_balance_areas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('lat', sa.Float(), nullable=True),
        sa.Column('lng', sa.Float(), nullable=True),
        sa.Column('polygon_wkt', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_market_balance_areas_code'), 'market_balance_areas', ['code'], unique=False)
    op.create_index(op.f('ix_market_balance_areas_id'), 'market_balance_areas', ['id'], unique=False)
    
    # Create control_areas table
    op.create_table('control_areas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('lat', sa.Float(), nullable=True),
        sa.Column('lng', sa.Float(), nullable=True),
        sa.Column('polygon_wkt', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_control_areas_code'), 'control_areas', ['code'], unique=False)
    op.create_index(op.f('ix_control_areas_id'), 'control_areas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop control_areas table
    op.drop_index(op.f('ix_control_areas_id'), table_name='control_areas')
    op.drop_index(op.f('ix_control_areas_code'), table_name='control_areas')
    op.drop_table('control_areas')
    
    # Drop market_balance_areas table
    op.drop_index(op.f('ix_market_balance_areas_id'), table_name='market_balance_areas')
    op.drop_index(op.f('ix_market_balance_areas_code'), table_name='market_balance_areas')
    op.drop_table('market_balance_areas')
    
    # Drop bidzones table
    op.drop_index(op.f('ix_bidzones_id'), table_name='bidzones')
    op.drop_index(op.f('ix_bidzones_code'), table_name='bidzones')
    op.drop_table('bidzones')
    
    # Drop regions table
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_index(op.f('ix_regions_code'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ### 