"""add country_id to control_areas

Revision ID: aa90cb1f965b
Revises: 4aeb61709380
Create Date: 2025-07-21 00:55:07.992761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa90cb1f965b'
down_revision = '4aeb61709380'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_areas', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_control_areas_country_id'), 'control_areas', ['country_id'], unique=False)
    op.create_foreign_key(None, 'control_areas', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'control_areas', type_='foreignkey')
    op.drop_index(op.f('ix_control_areas_country_id'), table_name='control_areas')
    op.drop_column('control_areas', 'country_id')
    # ### end Alembic commands ### 