"""add elexon generation data table

Revision ID: b1ec56c9e900
Revises: 6d741fe92636
Create Date: 2025-08-17 14:42:31.943375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ec56c9e900'
down_revision = '6d741fe92636'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elexon_generation_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('bm_unit', sa.String(length=50), nullable=False),
    sa.Column('settlement_period', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('generation_unit_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['generation_unit_id'], ['generation_units.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_elexon_data_timestamp_bm_unit', 'elexon_generation_data', ['timestamp', 'bm_unit'], unique=False)
    op.create_index('idx_elexon_data_timestamp_bm_unit_period', 'elexon_generation_data', ['timestamp', 'bm_unit', 'settlement_period'], unique=False)
    op.create_index(op.f('ix_elexon_generation_data_bm_unit'), 'elexon_generation_data', ['bm_unit'], unique=False)
    op.create_index(op.f('ix_elexon_generation_data_settlement_period'), 'elexon_generation_data', ['settlement_period'], unique=False)
    op.create_index(op.f('ix_elexon_generation_data_timestamp'), 'elexon_generation_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_elexon_generation_data_timestamp'), table_name='elexon_generation_data')
    op.drop_index(op.f('ix_elexon_generation_data_settlement_period'), table_name='elexon_generation_data')
    op.drop_index(op.f('ix_elexon_generation_data_bm_unit'), table_name='elexon_generation_data')
    op.drop_index('idx_elexon_data_timestamp_bm_unit_period', table_name='elexon_generation_data')
    op.drop_index('idx_elexon_data_timestamp_bm_unit', table_name='elexon_generation_data')
    op.drop_table('elexon_generation_data')
    # ### end Alembic commands ### 