"""Add foreign key relationship between generation_units and windfarms

Revision ID: bbf9e212aca5
Revises: befe9ca8b34e
Create Date: 2025-07-30 18:56:43.133380

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "bbf9e212aca5"
down_revision = "befe9ca8b34e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_generation_units_windfarm_id", "generation_units", "windfarms", ["windfarm_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_generation_units_windfarm_id", "generation_units", type_="foreignkey")
    # ### end Alembic commands ###
