"""Make state_id nullable in windfarms table

Revision ID: befe9ca8b34e
Revises: add_power_generation_data
Create Date: 2025-07-30 15:45:39.000706

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "befe9ca8b34e"
down_revision = "add_power_generation_data"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("windfarms", "state_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("windfarms", "state_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
