"""Add first_power_date field to generation_units

Revision ID: c561ddf39f2a
Revises: 348cb620b27f
Create Date: 2025-10-17 15:38:13.945106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c561ddf39f2a'
down_revision = '348cb620b27f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_units', sa.Column('first_power_date', sa.Date(), nullable=True))
    # Note: Removed index modification to avoid duplicate key error
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_units', 'first_power_date')
    # ### end Alembic commands ### 