"""Add start_date and end_date to generation_units

Revision ID: cdf860f8f78d
Revises: add_celery_task_id
Create Date: 2025-09-05 16:35:59.026562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf860f8f78d'
down_revision = 'add_celery_task_id'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_units', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('generation_units', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_units', 'end_date')
    op.drop_column('generation_units', 'start_date')
    # ### end Alembic commands ### 