"""add unique constraint for generation_data_raw upserts

Revision ID: e385cc409e83
Revises: c561ddf39f2a
Create Date: 2025-10-19 04:07:59.994559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e385cc409e83'
down_revision = 'c561ddf39f2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add unique constraint for generation_data_raw (skip generation_units.code)
    op.create_unique_constraint(
        'uq_generation_data_raw_source_identifier_period',
        'generation_data_raw',
        ['source', 'identifier', 'period_start']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove unique constraint
    op.drop_constraint('uq_generation_data_raw_source_identifier_period', 'generation_data_raw', type_='unique')
    # ### end Alembic commands ### 