"""Add entsoe_fetch_history table

Revision ID: f9527490e4ad
Revises: 2cee37de516d
Create Date: 2025-07-30 03:33:33.244382

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f9527490e4ad"
down_revision = "2cee37de516d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entsoe_fetch_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_type", sa.String(length=50), nullable=False),
        sa.Column("start_datetime", sa.DateTime(), nullable=False),
        sa.Column("end_datetime", sa.DateTime(), nullable=False),
        sa.Column("area_code", sa.String(length=100), nullable=False),
        sa.Column("production_type", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("records_fetched", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("requested_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entsoe_fetch_history_id"), "entsoe_fetch_history", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_entsoe_fetch_history_id"), table_name="entsoe_fetch_history")
    op.drop_table("entsoe_fetch_history")
    # ### end Alembic commands ###
