"""Add ENTSOE data coverage tracking

Revision ID: fc43705b1340
Revises: 16ef6dbd8674
Create Date: 2025-08-17 12:28:19.887784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc43705b1340'
down_revision = '16ef6dbd8674'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 