#!/usr/bin/env python3
"""
Seed script for owners table
"""
from sqlalchemy.orm import Session

from app.models.owner import Owner


# Mapping function to convert detailed types to schema-allowed types
def map_owner_type(detailed_type: str) -> str:
    """Map detailed owner types to schema-allowed values"""
    type_mapping = {
        # Utility types
        "UTILITY": "utility",
        # Private equity and investment types
        "PE": "private_equity",
        "ASSET_MGMT": "private_equity",
        "INFRA_FUND": "private_equity",
        "PENSION": "private_equity",
        "INSURANCE": "private_equity",
        # Oil, gas and energy types
        "ENERGY": "oil_and_gas",
        "OIL_GAS": "oil_and_gas",
        # Investment fund types
        "BANK": "investment_fund",
        "GOVT": "investment_fund",
        "CORP": "investment_fund",
        "DEVELOPER": "investment_fund",
        "RESEARCH": "investment_fund",
        "CONSORTIUM": "investment_fund",
        "COOP": "investment_fund",
        "FIN_SVCS": "investment_fund",
        "UNKNOWN": "investment_fund",
    }
    return type_mapping.get(detailed_type, "investment_fund")


OWNERS_DATA = [
    {
        "name": "1st Energy Technologies",
        "code": "1ST_ENERGY_TECH",
        "type": "ENERGY",
        "notes": "Renewable energy technology company focused on innovative solutions for wind and solar projects.",
    },
    {
        "name": "AIP Management",
        "code": "AIP_MGMT",
        "type": "ASSET_MGMT",
        "notes": "Alternative Investment Partners - Asset management firm specializing in infrastructure investments.",
    },
    {
        "name": "Akershus Energi",
        "code": "AKERSHUS_ENERGY",
        "type": "UTILITY",
        "notes": "Norwegian energy company owned by Akershus County, active in renewable energy production and district heating.",
    },
    {
        "name": "Akita Bank",
        "code": "AKITA_BANK",
        "type": "BANK",
        "notes": "Japanese regional bank involved in renewable energy project financing.",
    },
    {
        "name": "Allianz Capital Partners",
        "code": "ALLIANZ_CAP_PRTNRS",
        "type": "PE",
        "notes": "Investment arm of Allianz Group, one of Europe's largest insurance companies, managing alternative investments including renewable energy infrastructure.",
    },
    {
        "name": "ALTE LEIPZIGER-HALLESCHE",
        "code": "ALTE_LEIPZIGER_HALLESCHE",
        "type": "INSURANCE",
        "notes": "German insurance group investing in renewable energy infrastructure as part of their sustainable investment strategy.",
    },
    {
        "name": "AMF",
        "code": "AMF",
        "type": "PENSION",
        "notes": "Swedish pension fund (Pensionsförsäkringsaktiebolaget) managing occupational pensions with significant renewable energy investments.",
    },
    {
        "name": "Andel",
        "code": "ANDEL",
        "type": "COOP",
        "notes": "Cooperative energy company model, typically found in Denmark for community-owned renewable projects.",
    },
    {
        "name": "APG Asset Management",
        "code": "APG_ASSET_MGMT",
        "type": "PENSION",
        "notes": "Largest pension fund asset manager in the Netherlands, managing over €500 billion including significant renewable energy infrastructure.",
    },
    {
        "name": "Aquila Capital",
        "code": "AQUILA_CAP",
        "type": "ASSET_MGMT",
        "notes": "Hamburg-based investment manager specializing in renewable energy, infrastructure and sustainable agriculture investments.",
    },
    {
        "name": "Ardian",
        "code": "ARDIAN",
        "type": "PE",
        "notes": "Leading European private investment house with €150+ billion AUM, active in renewable energy infrastructure investments.",
    },
    {
        "name": "Arjun Infrastructure Partners",
        "code": "ARJUN_INFRA_PRTNRS",
        "type": "INFRA_FUND",
        "notes": "UK-based infrastructure investment firm focused on mid-market renewable energy and infrastructure assets in Europe.",
    },
    {
        "name": "Ärzteversorgung Westfalen-Lippe",
        "code": "AERZTEVERSORGUNG_WL",
        "type": "PENSION",
        "notes": "German medical professionals' pension fund investing in renewable energy infrastructure for long-term returns.",
    },
    {
        "name": "ASKO Fornybar",
        "code": "ASKO_FORNYBAR",
        "type": "ENERGY",
        "notes": "Norwegian renewable energy company, subsidiary of NorgesGruppen, developing wind and solar projects.",
    },
    {
        "name": "Aspiravi",
        "code": "ASPIRAVI",
        "type": "ENERGY",
        "notes": "Belgian renewable energy company specializing in onshore and offshore wind projects, owned by municipalities.",
    },
    {
        "name": "AXA IM Alts",
        "code": "AXA_IM_ALTS",
        "type": "ASSET_MGMT",
        "notes": "Alternative investment arm of AXA Investment Managers with €184 billion AUM, active in renewable energy infrastructure.",
    },
    {
        "name": "Axpo",
        "code": "AXPO",
        "type": "UTILITY",
        "notes": "Switzerland's largest producer of renewable energy, international energy trader active in wind and solar development.",
    },
    {
        "name": "B. Grimm Power",
        "code": "B_GRIMM_PWR",
        "type": "ENERGY",
        "notes": "Thai power generation company, part of B.Grimm Group, developing renewable energy projects across Southeast Asia.",
    },
    {
        "name": "BAE Systems Pension Funds",
        "code": "BAE_SYSTEMS_PENSION",
        "type": "PENSION",
        "notes": "UK aerospace and defense company's pension scheme investing in renewable energy infrastructure.",
    },
    {
        "name": "Banque des Territoires",
        "code": "BANQUE_DES_TERRITOIRES",
        "type": "GOVT",
        "notes": "French public financial institution supporting regional development including renewable energy infrastructure.",
    },
    {
        "name": "Baram",
        "code": "BARAM",
        "type": "DEVELOPER",
        "notes": "Renewable energy project developer.",
    },
    {
        "name": "BASF",
        "code": "BASF",
        "type": "CORP",
        "notes": "German chemical company investing in renewable energy to power operations and meet sustainability targets.",
    },
    {
        "name": "BKW",
        "code": "BKW",
        "type": "UTILITY",
        "notes": "Swiss energy and infrastructure company operating renewable energy assets across Europe.",
    },
    {
        "name": "Bouygues Travaux Publics",
        "code": "BOUYGUES_TRAVAUX_PUB",
        "type": "CORP",
        "notes": "Major French construction company involved in renewable energy infrastructure development.",
    },
    {
        "name": "Brockwell Energy",
        "code": "BROCKWELL_ENERGY",
        "type": "ENERGY",
        "notes": "UK-based renewable energy developer focused on solar and wind projects.",
    },
    {
        "name": "Brookfield",
        "code": "BROOKFIELD",
        "type": "ASSET_MGMT",
        "notes": "Global alternative asset manager with $850+ billion AUM, major investor in renewable power infrastructure worldwide.",
    },
    {
        "name": "Bruntwood Group",
        "code": "BRUNTWOOD_GROUP",
        "type": "CORP",
        "notes": "UK property company investing in renewable energy for sustainable real estate development.",
    },
    {
        "name": "BW Ideol",
        "code": "BW_IDEOL",
        "type": "ENERGY",
        "notes": "Floating offshore wind technology company, leader in floating wind foundation design and engineering.",
    },
    {
        "name": "Caisse des Dépôts",
        "code": "CAISSE_DES_DEPOTS",
        "type": "GOVT",
        "notes": "French public financial institution managing public interest investments including renewable energy infrastructure.",
    },
    {
        "name": "Capital Dynamics",
        "code": "CAP_DYNAMICS",
        "type": "PE",
        "notes": "Global private asset management firm with significant clean energy infrastructure investments.",
    },
    {
        "name": "Cathay PE",
        "code": "CATHAY_PE",
        "type": "PE",
        "notes": "Taiwan-based private equity firm investing in renewable energy projects across Asia.",
    },
    {
        "name": "Cathay Wind Power",
        "code": "CATHAY_WIND_PWR",
        "type": "ENERGY",
        "notes": "Taiwanese wind power developer and operator, subsidiary of Cathay Financial Holdings.",
    },
    {
        "name": "CDPQ",
        "code": "CDPQ",
        "type": "PENSION",
        "notes": "Caisse de dépôt et placement du Québec - One of Canada's largest pension fund managers with significant renewable energy portfolio.",
    },
    {
        "name": "China Resources",
        "code": "CHINA_RESOURCES",
        "type": "CORP",
        "notes": "Chinese state-owned conglomerate with major power generation business including renewable energy.",
    },
    {
        "name": "China Steel Corporation",
        "code": "CHINA_STEEL_CORP",
        "type": "CORP",
        "notes": "Taiwan's largest steel producer investing in renewable energy for sustainable operations.",
    },
    {
        "name": "China Three Gorges",
        "code": "CHINA_THREE_GORGES",
        "type": "UTILITY",
        "notes": "Chinese state-owned power company, world's largest hydropower developer expanding into wind and solar.",
    },
    {
        "name": "Chubu Electric",
        "code": "CHUBU_ELEC",
        "type": "UTILITY",
        "notes": "Japanese electric utility serving central Japan, developing renewable energy projects domestically and internationally.",
    },
    {
        "name": "CLAL Insurance",
        "code": "CLAL_INSURANCE",
        "type": "INSURANCE",
        "notes": "Israeli insurance company investing in renewable energy infrastructure.",
    },
    {
        "name": "Cloudberry Clean Energy",
        "code": "CLOUDBERRY_CLEAN_ENERGY",
        "type": "ENERGY",
        "notes": "Nordic renewable energy company owning and operating hydro and wind power assets in Norway and Sweden.",
    },
    {
        "name": "Cobra Group",
        "code": "COBRA_GROUP",
        "type": "CORP",
        "notes": "Spanish industrial and energy services company, part of ACS Group, developing renewable energy projects globally.",
    },
    {
        "name": "Commerz Real",
        "code": "COMMERZ_REAL",
        "type": "ASSET_MGMT",
        "notes": "German asset manager, subsidiary of Commerzbank, investing in renewable energy infrastructure.",
    },
    {
        "name": "Community Windpower",
        "code": "COMMUNITY_WINDPWR",
        "type": "DEVELOPER",
        "notes": "UK wind farm developer focusing on community-based renewable energy projects.",
    },
    {
        "name": "Copenhagen Infrastructure Partners (CIP)",
        "code": "CIP",
        "type": "INFRA_FUND",
        "notes": "World's largest dedicated fund manager within renewable energy infrastructure with €25+ billion under management.",
    },
    {
        "name": "Cosmo Eco Power",
        "code": "COSMO_ECO_PWR",
        "type": "ENERGY",
        "notes": "Japanese renewable energy developer and operator focusing on wind power projects.",
    },
    {
        "name": "Crédit Agricole Assurances",
        "code": "CREDIT_AGRICOLE_ASSURANCES",
        "type": "INSURANCE",
        "notes": "Insurance arm of Crédit Agricole Group, major investor in European renewable energy infrastructure.",
    },
    {
        "name": "Cube Infrastructure Managers",
        "code": "CUBE_INFRA_MANAGERS",
        "type": "INFRA_FUND",
        "notes": "Independent European infrastructure fund manager with focus on essential infrastructure including renewables.",
    },
    {
        "name": "Daiwa Energy & Infrastructure",
        "code": "DAIWA_ENERGY_AND_INFRA",
        "type": "ASSET_MGMT",
        "notes": "Japanese financial services company's infrastructure investment arm focusing on renewable energy.",
    },
    {
        "name": "Dalane Vind",
        "code": "DALANE_VIND",
        "type": "ENERGY",
        "notes": "Norwegian wind power developer and operator in the Dalane region.",
    },
    {
        "name": "Dalmore Capital",
        "code": "DALMORE_CAP",
        "type": "INFRA_FUND",
        "notes": "UK infrastructure investment manager focused on essential infrastructure including renewable energy.",
    },
    {
        "name": "DBJ",
        "code": "DBJ",
        "type": "BANK",
        "notes": "Development Bank of Japan providing financing for renewable energy infrastructure projects.",
    },
    {
        "name": "De Vlaamse Energieholding (VEH)",
        "code": "VEH",
        "type": "GOVT",
        "notes": "Flemish government energy holding company investing in renewable energy projects in Belgium.",
    },
    {
        "name": "DEME",
        "code": "DEME",
        "type": "CORP",
        "notes": "Belgian marine engineering company specializing in offshore wind farm construction and maintenance.",
    },
    {
        "name": "Dominion Energy",
        "code": "DOMINION_ENERGY",
        "type": "UTILITY",
        "notes": "US energy company developing large-scale offshore wind projects along the US East Coast.",
    },
    {
        "name": "Ecole Centrale de Nantes",
        "code": "ECOLE_CENTRALE_NANTES",
        "type": "RESEARCH",
        "notes": "French engineering school with marine renewable energy research facilities including SEM-REV test site.",
    },
    {
        "name": "EDF",
        "code": "EDF",
        "type": "UTILITY",
        "notes": "Électricité de France - French multinational electric utility, one of the world's largest producers of renewable energy.",
    },
    {
        "name": "Eidsiva Energi",
        "code": "EIDSIVA_ENERGY",
        "type": "UTILITY",
        "notes": "Norwegian energy company owned by municipalities, producing hydroelectric and wind power.",
    },
    {
        "name": "Elektrizitätswerk Der Stadt Zürich (EWZ)",
        "code": "EWZ",
        "type": "UTILITY",
        "notes": "Zurich's municipal utility company investing in renewable energy projects across Europe.",
    },
    {
        "name": "Elicio",
        "code": "ELICIO",
        "type": "DEVELOPER",
        "notes": "Belgian renewable energy developer, now part of Nethys group, focusing on wind energy projects.",
    },
    {
        "name": "Enbridge",
        "code": "ENBRIDGE",
        "type": "ENERGY",
        "notes": "North American energy infrastructure company with growing renewable power generation portfolio.",
    },
    {
        "name": "EnBW",
        "code": "ENBW",
        "type": "UTILITY",
        "notes": "Energie Baden-Württemberg - Major German energy company developing offshore wind projects in North and Baltic Seas.",
    },
    {
        "name": "Eneco",
        "code": "ENECO",
        "type": "UTILITY",
        "notes": "Dutch energy company owned by Mitsubishi and Chubu Electric, major player in European wind energy.",
    },
    {
        "name": "ENEOS",
        "code": "ENEOS",
        "type": "ENERGY",
        "notes": "Japanese petroleum company expanding into renewable energy including offshore wind development.",
    },
    {
        "name": "Energy Infrastructure Partners (EIP)",
        "code": "EIP",
        "type": "INFRA_FUND",
        "notes": "Swiss infrastructure investment manager focusing on renewable energy assets across Europe.",
    },
    {
        "name": "EnerOcean",
        "code": "ENEROCEAN",
        "type": "ENERGY",
        "notes": "Spanish floating wind technology developer working on innovative offshore wind solutions.",
    },
    {
        "name": "Engie",
        "code": "ENGIE",
        "type": "UTILITY",
        "notes": "French multinational utility company, global leader in renewable energy development and operation.",
    },
    {
        "name": "ENOVA",
        "code": "ENOVA",
        "type": "GOVT",
        "notes": "Norwegian government enterprise promoting sustainable energy solutions and supporting renewable projects.",
    },
    {
        "name": "Entega",
        "code": "ENTEGA",
        "type": "UTILITY",
        "notes": "German energy provider focusing on renewable energy supply and infrastructure.",
    },
    {
        "name": "Eolink",
        "code": "EOLINK",
        "type": "ENERGY",
        "notes": "French floating wind technology company developing innovative pyramid-shaped floating wind turbines.",
    },
    {
        "name": "Equinor",
        "code": "EQUINOR",
        "type": "ENERGY",
        "notes": "Norwegian state-owned energy company, pioneer in floating offshore wind technology with Hywind projects.",
    },
    {
        "name": "Equitix",
        "code": "EQUITIX",
        "type": "INFRA_FUND",
        "notes": "UK infrastructure fund manager investing in core infrastructure including renewable energy projects.",
    },
    {
        "name": "ERG",
        "code": "ERG",
        "type": "ENERGY",
        "notes": "Italian renewable energy company operating wind, solar and hydroelectric plants across Europe.",
    },
    {
        "name": "ESB",
        "code": "ESB",
        "type": "UTILITY",
        "notes": "Electricity Supply Board - Irish state-owned electricity company developing renewable projects internationally.",
    },
    {
        "name": "Esteyco",
        "code": "ESTEYCO",
        "type": "CORP",
        "notes": "Spanish engineering company specializing in innovative concrete solutions for offshore wind foundations.",
    },
    {
        "name": "European Energy",
        "code": "EUROPEAN_ENERGY",
        "type": "DEVELOPER",
        "notes": "Danish renewable energy developer and operator with projects across Europe, Americas and Asia-Pacific.",
    },
    {
        "name": "Eurus Energy",
        "code": "EURUS_ENERGY",
        "type": "ENERGY",
        "notes": "Joint venture between Toyota Tsusho and Tokyo Electric Power developing wind projects globally.",
    },
    {
        "name": "Eviny",
        "code": "EVINY",
        "type": "UTILITY",
        "notes": "Norwegian energy company (formerly BKK) producing renewable energy from hydro and wind sources.",
    },
    {
        "name": "EWE",
        "code": "EWE",
        "type": "UTILITY",
        "notes": "German energy and telecommunications company developing offshore wind projects in German waters.",
    },
    {
        "name": "ewz",
        "code": "EWZ_DUPLICATE",
        "type": "UTILITY",
        "notes": "See Elektrizitätswerk Der Stadt Zürich (EWZ) - Duplicate entry.",
    },
    {
        "name": "Finnmark Kraft",
        "code": "FINNMARK_KRAFT",
        "type": "UTILITY",
        "notes": "Norwegian regional energy company operating renewable energy assets in northern Norway.",
    },
    {
        "name": "Fortum",
        "code": "FORTUM",
        "type": "UTILITY",
        "notes": "Finnish state-owned energy company focusing on clean energy including hydro, wind and solar power.",
    },
    {
        "name": "Fraunhoffer-IWES",
        "code": "FRAUNHOFFER_IWES",
        "type": "RESEARCH",
        "notes": "Fraunhofer Institute for Wind Energy Systems - Leading German research institute for wind energy technology.",
    },
    {
        "name": "Fred. Olsen Renewables",
        "code": "FRED_OLSEN_REN",
        "type": "DEVELOPER",
        "notes": "Norwegian renewable energy company with wind farms across UK, Ireland, Norway and Sweden.",
    },
    {
        "name": "Fukushima Consortium",
        "code": "FUKUSHIMA_CONSORTIUM",
        "type": "CONSORTIUM",
        "notes": "Japanese consortium developing floating offshore wind demonstration projects off Fukushima coast.",
    },
    {
        "name": "Fuyo Ocean Development & Engineering",
        "code": "FUYO_OCEAN_DEV",
        "type": "CORP",
        "notes": "Japanese marine engineering company involved in offshore wind development.",
    },
    {
        "name": "GE Renewable Energy",
        "code": "GE_REN_ENERGY",
        "type": "CORP",
        "notes": "General Electric's renewable energy division, major wind turbine manufacturer including Haliade-X offshore turbines.",
    },
    {
        "name": "Gentari",
        "code": "GENTARI",
        "type": "ENERGY",
        "notes": "Clean energy subsidiary of PETRONAS focusing on renewable energy, hydrogen and green mobility solutions.",
    },
    {
        "name": "GHENOVA",
        "code": "GHENOVA",
        "type": "CORP",
        "notes": "Spanish engineering company providing design and consulting services for offshore wind projects.",
    },
    {
        "name": "Gingko Tree Investment",
        "code": "GINGKO_TREE_INV",
        "type": "ASSET_MGMT",
        "notes": "Investment firm focusing on sustainable and renewable energy infrastructure.",
    },
    {
        "name": "Glennmont Partners",
        "code": "GLENNMONT_PRTNRS",
        "type": "INFRA_FUND",
        "notes": "European renewable energy fund manager with €3.5+ billion raised across funds, now part of Nuveen.",
    },
    {
        "name": "GLIL Infrastructure",
        "code": "GLIL_INFRA",
        "type": "PENSION",
        "notes": "UK local government pension scheme infrastructure investment platform focusing on renewable energy.",
    },
    {
        "name": "Global Power Synergy (GPSC)",
        "code": "GPSC",
        "type": "ENERGY",
        "notes": "Thai power generation company, subsidiary of PTT, developing renewable energy projects in Asia.",
    },
    {
        "name": "Globaleye Ventures",
        "code": "GLOBALEYE_VENTURES",
        "type": "PE",
        "notes": "Venture capital firm investing in renewable energy and clean technology companies.",
    },
    {
        "name": "Gothaer Leben Renewables",
        "code": "GOTHAER_LEBEN_REN",
        "type": "INSURANCE",
        "notes": "German insurance company's renewable energy investment arm.",
    },
    {
        "name": "Green Giraffe",
        "code": "GREEN_GIRAFFE",
        "type": "CORP",
        "notes": "Specialist renewable energy financial advisory firm supporting project development and financing.",
    },
    {
        "name": "Green Offshore",
        "code": "GREEN_OFFSHORE",
        "type": "DEVELOPER",
        "notes": "Offshore wind project developer focusing on floating wind technology.",
    },
    {
        "name": "Green Power Investment Corporation",
        "code": "GREEN_PWR_INV",
        "type": "CORP",
        "notes": "Renewable energy investment company developing green power projects.",
    },
    {
        "name": "Gudbrandsdal Energi",
        "code": "GUDBRANDSDAL_ENERGY",
        "type": "UTILITY",
        "notes": "Norwegian regional energy company producing hydroelectric and wind power.",
    },
    {
        "name": "Gulf Energy Development Public Co",
        "code": "GULF_ENERGY_DEV",
        "type": "ENERGY",
        "notes": "Thai independent power producer developing renewable energy projects across Southeast Asia.",
    },
    {
        "name": "Hanwha Nandong Power Generation",
        "code": "HANWHA_NANDONG_PWR",
        "type": "ENERGY",
        "notes": "South Korean power generation company, part of Hanwha Group, investing in renewable energy.",
    },
    {
        "name": "Harboøre",
        "code": "HARBOOERE",
        "type": "COOP",
        "notes": "Danish wind energy cooperative, one of the early community wind projects in Denmark.",
    },
    {
        "name": "Harbour Energy",
        "code": "HARBOUR_ENERGY",
        "type": "ENERGY",
        "notes": "UK North Sea oil and gas company transitioning into renewable energy investments.",
    },
    {
        "name": "Hitachi",
        "code": "HITACHI",
        "type": "CORP",
        "notes": "Japanese conglomerate with energy division developing wind turbines and renewable energy solutions.",
    },
    {
        "name": "HOFOR",
        "code": "HOFOR",
        "type": "UTILITY",
        "notes": "Greater Copenhagen utility company investing in renewable energy including offshore wind.",
    },
    {
        "name": "Hokuriku Electric Power",
        "code": "HOKURIKU_ELEC_PWR",
        "type": "UTILITY",
        "notes": "Japanese regional utility serving Hokuriku region, developing renewable energy projects.",
    },
    {
        "name": "Hokutaku",
        "code": "HOKUTAKU",
        "type": "CORP",
        "notes": "Japanese company involved in renewable energy development.",
    },
    {
        "name": "hvc",
        "code": "HVC",
        "type": "UTILITY",
        "notes": "Dutch waste and energy company investing in renewable energy solutions.",
    },
    {
        "name": "Hyundai E&C",
        "code": "HYUNDAI_ENC",
        "type": "CORP",
        "notes": "Hyundai Engineering & Construction - South Korean company involved in renewable energy infrastructure projects.",
    },
    {
        "name": "Iberdrola",
        "code": "IBERDROLA",
        "type": "UTILITY",
        "notes": "Spanish multinational electric utility, one of the world's largest renewable energy producers and offshore wind leaders.",
    },
    {
        "name": "Idemitsu",
        "code": "IDEMITSU",
        "type": "ENERGY",
        "notes": "Japanese petroleum company expanding into renewable energy including offshore wind development.",
    },
    {
        "name": "Ignitis Renewables",
        "code": "IGNITIS_REN",
        "type": "DEVELOPER",
        "notes": "Lithuanian state-owned energy group's renewable development arm active in Baltic and Polish markets.",
    },
    {
        "name": "IKEA",
        "code": "IKEA",
        "type": "CORP",
        "notes": "Swedish furniture retailer investing in renewable energy for operations and as standalone investments.",
    },
    {
        "name": "Industriens Pension (IP)",
        "code": "INDUSTRIENS_PENSION",
        "type": "PENSION",
        "notes": "Danish pension fund for industry workers with significant renewable energy infrastructure investments.",
    },
    {
        "name": "InfraRed",
        "code": "INFRARED",
        "type": "INFRA_FUND",
        "notes": "International infrastructure investment manager with focus on renewable energy assets.",
    },
    {
        "name": "INGETEAM",
        "code": "INGETEAM",
        "type": "CORP",
        "notes": "Spanish company specializing in power and control electronics for renewable energy including wind converters.",
    },
    {
        "name": "Ingka Group",
        "code": "INGKA_GROUP",
        "type": "CORP",
        "notes": "Largest IKEA retailer investing heavily in renewable energy including wind and solar farms.",
    },
    {
        "name": "Innovent",
        "code": "INNOVENT",
        "type": "DEVELOPER",
        "notes": "French renewable energy developer specializing in wind power projects.",
    },
    {
        "name": "INPEX",
        "code": "INPEX",
        "type": "ENERGY",
        "notes": "Japanese oil and gas company diversifying into renewable energy including offshore wind.",
    },
    {
        "name": "Investri Offshore",
        "code": "INVESTRI_OFFSHORE",
        "type": "DEVELOPER",
        "notes": "Offshore wind project developer and investor.",
    },
    {
        "name": "Itochu",
        "code": "ITOCHU",
        "type": "CORP",
        "notes": "Japanese trading company with renewable energy investments across multiple technologies and regions.",
    },
    {
        "name": "Japan Renewable Energy (JRE)",
        "code": "JRE",
        "type": "DEVELOPER",
        "notes": "Japanese renewable energy developer backed by Goldman Sachs, developing wind and solar projects.",
    },
    {
        "name": "Jeonnam Development Corporation",
        "code": "JEONNAM_DEV_CORP",
        "type": "GOVT",
        "notes": "South Korean regional development corporation investing in renewable energy infrastructure.",
    },
    {
        "name": "JERA",
        "code": "JERA",
        "type": "UTILITY",
        "notes": "Joint venture between TEPCO and Chubu Electric, Japan's largest power generation company expanding into renewables.",
    },
    {
        "name": "JERA Nex bp",
        "code": "JERA_NEX_BP",
        "type": "ENERGY",
        "notes": "Joint venture between JERA and BP for offshore wind development, combining expertise in power and offshore operations.",
    },
    {
        "name": "JFE Engineering",
        "code": "JFE_ENGINEERING",
        "type": "CORP",
        "notes": "Japanese engineering company involved in offshore wind foundation manufacturing and installation.",
    },
    {
        "name": "John Laing",
        "code": "JOHN_LAING",
        "type": "INFRA_FUND",
        "notes": "UK infrastructure investor with significant renewable energy portfolio, acquired by KKR in 2021.",
    },
    {
        "name": "J-Power",
        "code": "J_PWR",
        "type": "UTILITY",
        "notes": "Electric Power Development Company - Japanese wholesale electric utility developing wind power projects.",
    },
    {
        "name": "Jysk Energi",
        "code": "JYSK_ENERGY",
        "type": "UTILITY",
        "notes": "Danish energy company focused on renewable energy production and distribution.",
    },
    {
        "name": "Kajima",
        "code": "KAJIMA",
        "type": "CORP",
        "notes": "Japanese construction company involved in offshore wind foundation and substation construction.",
    },
    {
        "name": "Kanpu",
        "code": "KANPU",
        "type": "ENERGY",
        "notes": "Japanese wind power developer and operator.",
    },
    {
        "name": "Kansai Electric Power",
        "code": "KANSAI_ELEC_PWR",
        "type": "UTILITY",
        "notes": "Japanese electric utility serving Kansai region, developing offshore wind projects in Japan and abroad.",
    },
    {
        "name": "Katokensetsu",
        "code": "KATOKENSETSU",
        "type": "CORP",
        "notes": "Japanese construction company involved in renewable energy infrastructure development.",
    },
    {
        "name": "KEPCO",
        "code": "KEPCO",
        "type": "UTILITY",
        "notes": "Korea Electric Power Corporation - South Korea's largest electric utility developing renewable projects globally.",
    },
    {
        "name": "KEPCO E&C",
        "code": "KEPCO_ENC",
        "type": "CORP",
        "notes": "KEPCO Engineering & Construction - Engineering subsidiary providing renewable energy project services.",
    },
    {
        "name": "KEPCO Research Institute (KEPRI)",
        "code": "KEPRI",
        "type": "RESEARCH",
        "notes": "Research arm of KEPCO focusing on renewable energy technologies and grid integration.",
    },
    {
        "name": "Keppel Corp and Keppel Infrastructure Fund",
        "code": "KEPPEL_CORP_AND",
        "type": "CORP",
        "notes": "Singaporean conglomerate with infrastructure arm investing in renewable energy projects across Asia.",
    },
    {
        "name": "KGAL",
        "code": "KGAL",
        "type": "ASSET_MGMT",
        "notes": "German investment management company specializing in real assets including renewable energy infrastructure.",
    },
    {
        "name": "Kirkbi",
        "code": "KIRKBI",
        "type": "CORP",
        "notes": "Investment company of LEGO founding family with significant renewable energy investments supporting carbon neutrality goals.",
    },
    {
        "name": "KLP",
        "code": "KLP",
        "type": "PENSION",
        "notes": "Norway's largest pension company investing in renewable energy infrastructure for sustainable returns.",
    },
    {
        "name": "Korea Institute of Energy (KIER)",
        "code": "KIER",
        "type": "RESEARCH",
        "notes": "Korean government research institute developing renewable energy technologies including offshore wind.",
    },
    {
        "name": "Korea Midland Power (KOMIPO)",
        "code": "KOMIPO",
        "type": "UTILITY",
        "notes": "South Korean power generation company, subsidiary of KEPCO, developing renewable energy projects.",
    },
    {
        "name": "Korea SE Power (KOEN)",
        "code": "KOEN",
        "type": "UTILITY",
        "notes": "Korea South-East Power - KEPCO subsidiary focusing on renewable energy development including offshore wind.",
    },
    {
        "name": "Kyoto University",
        "code": "KYOTO_UNIVERSITY",
        "type": "RESEARCH",
        "notes": "Leading Japanese university conducting renewable energy research including floating wind technology.",
    },
    {
        "name": "Kyowa Oil",
        "code": "KYOWA_OIL",
        "type": "ENERGY",
        "notes": "Japanese oil company diversifying into renewable energy sector.",
    },
    {
        "name": "Kyrkvinden Ekonomisk förening",
        "code": "KYRKVINDEN_EKONOMISK_FORENING",
        "type": "COOP",
        "notes": "Swedish economic cooperative involved in wind energy development.",
    },
    {
        "name": "Kyudenko",
        "code": "KYUDENKO",
        "type": "CORP",
        "notes": "Japanese electrical engineering company involved in renewable energy project construction and maintenance.",
    },
    {
        "name": "L&G NTR Clean Power Fund",
        "code": "LG_NTR_CLEAN",
        "type": "INFRA_FUND",
        "notes": "Legal & General and NTR joint clean power fund investing in renewable energy infrastructure.",
    },
    {
        "name": "Lægernes Pensionskasse",
        "code": "LAEGERNES_PENSIONSKASSE",
        "type": "PENSION",
        "notes": "Danish pension fund for medical doctors investing in renewable energy for sustainable returns.",
    },
    {
        "name": "Luxcara",
        "code": "LUXCARA",
        "type": "ASSET_MGMT",
        "notes": "Hamburg-based asset manager specializing in renewable energy investments across Europe.",
    },
    {
        "name": "Macquarie",
        "code": "MACQUARIE",
        "type": "ASSET_MGMT",
        "notes": "Australian financial services company with major renewable energy infrastructure investments globally through Green Investment Group.",
    },
    {
        "name": "Marine Energy Test Centre",
        "code": "MARINE_ENERGY_TEST",
        "type": "RESEARCH",
        "notes": "Testing facility for marine renewable energy technologies including floating wind systems.",
    },
    {
        "name": "Marubeni",
        "code": "MARUBENI",
        "type": "CORP",
        "notes": "Japanese trading company with significant renewable energy portfolio including offshore wind projects globally.",
    },
    {
        "name": "Masdar",
        "code": "MASDAR",
        "type": "ENERGY",
        "notes": "Abu Dhabi Future Energy Company - UAE's renewable energy company developing projects worldwide including offshore wind.",
    },
    {
        "name": "Meewind",
        "code": "MEEWIND",
        "type": "DEVELOPER",
        "notes": "Belgian offshore wind developer and operator.",
    },
    {
        "name": "Middelgrunden Cooperative",
        "code": "MIDDELGRUNDEN_COOPERATIVE",
        "type": "COOP",
        "notes": "Danish wind cooperative owning 50% of Middelgrunden offshore wind farm near Copenhagen.",
    },
    {
        "name": "Mirova Eurofideme",
        "code": "MIROVA_EUROFIDEME",
        "type": "ASSET_MGMT",
        "notes": "Sustainable investment manager, affiliate of Natixis, focusing on renewable energy infrastructure.",
    },
    {
        "name": "Mitsubishi",
        "code": "MITSUBISHI",
        "type": "CORP",
        "notes": "Japanese conglomerate with renewable energy investments through various subsidiaries including offshore wind.",
    },
    {
        "name": "Mitsubishi HC Capital",
        "code": "MITSUBISHI_HC_CAP",
        "type": "FIN_SVCS",
        "notes": "Japanese financial services company providing leasing and financing for renewable energy projects.",
    },
    {
        "name": "Mitsubishi HI",
        "code": "MITSUBISHI_HI",
        "type": "CORP",
        "notes": "Mitsubishi Heavy Industries - Major manufacturer of wind turbines through MHI Vestas Offshore Wind joint venture.",
    },
    {
        "name": "Mitsui OSK Lines",
        "code": "MITSUI_OSK_LINES",
        "type": "CORP",
        "notes": "Japanese shipping company involved in offshore wind installation vessels and maintenance services.",
    },
    {
        "name": "MODEC",
        "code": "MODEC",
        "type": "CORP",
        "notes": "Japanese company specializing in floating production systems, expanding into floating wind platforms.",
    },
    {
        "name": "Municipal utilities",
        "code": "MUNICIPAL_UTILITIES",
        "type": "UTILITY",
        "notes": "Various municipal-owned utilities investing in renewable energy for local communities.",
    },
    {
        "name": "Myeongwoon Industry",
        "code": "MYEONGWOON_INDUSTRY",
        "type": "CORP",
        "notes": "South Korean industrial company involved in renewable energy component manufacturing.",
    },
    {
        "name": "Nadara",
        "code": "NADARA",
        "type": "DEVELOPER",
        "notes": "Renewable energy project developer and operator.",
    },
    {
        "name": "National Marine Research Institute",
        "code": "NATIONAL_MARINE_RESEARCH",
        "type": "RESEARCH",
        "notes": "Research institution studying marine conditions for offshore renewable energy development.",
    },
    {
        "name": "NEDO Consortium",
        "code": "NEDO_CONSORTIUM",
        "type": "CONSORTIUM",
        "notes": "New Energy and Industrial Technology Development Organization - Japanese government R&D funding organization.",
    },
    {
        "name": "Nethys",
        "code": "NETHYS",
        "type": "CORP",
        "notes": "Belgian holding company with investments in renewable energy through subsidiaries like Elicio.",
    },
    {
        "name": "Nissum Bredning",
        "code": "NISSUM_BREDNING",
        "type": "ENERGY",
        "notes": "Danish wind energy project in Nissum Bredning area.",
    },
    {
        "name": "Nordic Wind Power",
        "code": "NORDIC_WIND_PWR",
        "type": "DEVELOPER",
        "notes": "Scandinavian wind power developer and operator.",
    },
    {
        "name": "Norges Bank Investment Management",
        "code": "NORGES_BANK_INV",
        "type": "GOVT",
        "notes": "Manager of Norwegian sovereign wealth fund with significant renewable energy infrastructure investments globally.",
    },
    {
        "name": "Norsk Vind",
        "code": "NORSK_VIND",
        "type": "DEVELOPER",
        "notes": "Norwegian wind power developer focusing on onshore wind projects in Norway.",
    },
    {
        "name": "Norsk Vindpro",
        "code": "NORSK_VINDPRO",
        "type": "DEVELOPER",
        "notes": "Norwegian wind project development company.",
    },
    {
        "name": "Northland Power",
        "code": "NORTHLAND_PWR",
        "type": "ENERGY",
        "notes": "Canadian independent power producer with major offshore wind projects in Europe and Asia.",
    },
    {
        "name": "NTT Anode Energy",
        "code": "NTT_ANODE_ENERGY",
        "type": "ENERGY",
        "notes": "NTT Group's renewable energy subsidiary developing solar and wind projects to power data centers.",
    },
    {
        "name": "Nuhma",
        "code": "NUHMA",
        "type": "DEVELOPER",
        "notes": "Renewable energy developer and operator.",
    },
    {
        "name": "Obayashi",
        "code": "OBAYASHI",
        "type": "CORP",
        "notes": "Japanese construction company involved in offshore wind construction including foundations and substations.",
    },
    {
        "name": "Ocean Winds",
        "code": "OCEAN_WINDS",
        "type": "DEVELOPER",
        "notes": "Joint venture between EDPR and ENGIE dedicated to offshore wind development with 15GW+ portfolio.",
    },
    {
        "name": "Octopus Energy Generation",
        "code": "OCTOPUS_ENERGY_GENERATION",
        "type": "ENERGY",
        "notes": "UK renewable energy developer and operator, part of Octopus Group, with major onshore wind portfolio.",
    },
    {
        "name": "Ohmori",
        "code": "OHMORI",
        "type": "CORP",
        "notes": "Japanese company involved in renewable energy development.",
    },
    {
        "name": "OMV",
        "code": "OMV",
        "type": "ENERGY",
        "notes": "Austrian integrated oil and gas company transitioning to renewable energy including offshore wind.",
    },
    {
        "name": "ORE Catapult",
        "code": "ORE_CATAPULT",
        "type": "RESEARCH",
        "notes": "UK's Offshore Renewable Energy Catapult - technology innovation and research center for offshore renewable energy.",
    },
    {
        "name": "Orlen",
        "code": "ORLEN",
        "type": "ENERGY",
        "notes": "Polish oil refiner and petrol retailer expanding into offshore wind development in Baltic Sea.",
    },
    {
        "name": "Ørsted",
        "code": "ORSTED",
        "type": "UTILITY",
        "notes": "Danish multinational, world's largest developer of offshore wind power with projects across Europe, Americas and Asia.",
    },
    {
        "name": "Osaka Gas",
        "code": "OSAKA_GAS",
        "type": "UTILITY",
        "notes": "Japanese gas utility diversifying into renewable energy including offshore wind investments.",
    },
    {
        "name": "Ostfold Energi",
        "code": "OSTFOLD_ENERGY",
        "type": "UTILITY",
        "notes": "Norwegian regional energy company producing renewable energy from hydro and wind sources.",
    },
    {
        "name": "Otary",
        "code": "OTARY",
        "type": "DEVELOPER",
        "notes": "Belgian offshore wind developer and operator with projects in Belgian North Sea.",
    },
    {
        "name": "Pension Danmark",
        "code": "PENSION_DANMARK",
        "type": "PENSION",
        "notes": "Danish labor market pension fund with significant investments in renewable energy infrastructure.",
    },
    {
        "name": "Pensions Infrastructure Platform",
        "code": "PENSIONS_INFRA_PLATFORM",
        "type": "PENSION",
        "notes": "UK pension schemes' joint infrastructure investment platform including renewable energy assets.",
    },
    {
        "name": "Petoro",
        "code": "PETORO",
        "type": "GOVT",
        "notes": "Norwegian state-owned company managing government's oil and gas interests, exploring offshore wind opportunities.",
    },
    {
        "name": "PGGM",
        "code": "PGGM",
        "type": "PENSION",
        "notes": "Dutch pension fund service provider managing €300+ billion with significant renewable energy allocation.",
    },
    {
        "name": "PKA",
        "code": "PKA",
        "type": "PENSION",
        "notes": "Danish pension fund with major investments in renewable energy infrastructure including offshore wind.",
    },
    {
        "name": "Power at Sea",
        "code": "PWR_AT_SEA",
        "type": "DEVELOPER",
        "notes": "Offshore renewable energy developer focusing on floating wind and wave power technologies.",
    },
    {
        "name": "Provincje Fryslan",
        "code": "PROVINCJE_FRYSLAN",
        "type": "GOVT",
        "notes": "Dutch province of Friesland investing in local renewable energy projects.",
    },
    {
        "name": "PTTEP",
        "code": "PTTEP",
        "type": "ENERGY",
        "notes": "PTT Exploration and Production - Thai national oil company expanding into offshore wind development.",
    },
    {
        "name": "Renexia",
        "code": "RENEXIA",
        "type": "DEVELOPER",
        "notes": "Italian renewable energy developer specializing in offshore wind projects in Mediterranean Sea.",
    },
    {
        "name": "Repsol",
        "code": "REPSOL",
        "type": "ENERGY",
        "notes": "Spanish oil and gas company developing floating offshore wind projects as part of energy transition strategy.",
    },
    {
        "name": "Reventus Power",
        "code": "REVENTUS_PWR",
        "type": "DEVELOPER",
        "notes": "Renewable energy developer and operator.",
    },
    {
        "name": "RSK Group",
        "code": "RSK_GROUP",
        "type": "CORP",
        "notes": "Environmental, engineering and technical services group supporting renewable energy project development.",
    },
    {
        "name": "RWE",
        "code": "RWE",
        "type": "UTILITY",
        "notes": "German multinational energy company, one of world's largest renewable energy developers with major offshore wind portfolio.",
    },
    {
        "name": "Saibu Gas",
        "code": "SAIBU_GAS",
        "type": "UTILITY",
        "notes": "Japanese gas utility company diversifying into renewable energy sector.",
    },
    {
        "name": "Saitec",
        "code": "SAITEC",
        "type": "CORP",
        "notes": "Spanish engineering company developing innovative floating wind platform technology (SATH).",
    },
    {
        "name": "Samsø Kommune",
        "code": "SAMSO_KOMMUNE",
        "type": "GOVT",
        "notes": "Danish municipality known for renewable energy self-sufficiency including community wind projects.",
    },
    {
        "name": "Sankyo",
        "code": "SANKYO",
        "type": "CORP",
        "notes": "Japanese company involved in renewable energy development.",
    },
    {
        "name": "Sawakigumi",
        "code": "SAWAKIGUMI",
        "type": "CORP",
        "notes": "Japanese construction company involved in renewable energy infrastructure projects.",
    },
    {
        "name": "Schroders Greencoat",
        "code": "SCHRODERS_GREENCOAT",
        "type": "ASSET_MGMT",
        "notes": "UK renewable energy fund manager, now part of Schroders, managing wind and solar investments.",
    },
    {
        "name": "SDIC Red Rock Power",
        "code": "SDIC_RED_ROCK",
        "type": "ENERGY",
        "notes": "Chinese state-owned power investment company developing renewable energy projects.",
    },
    {
        "name": "SeaTwirl",
        "code": "SEATWIRL",
        "type": "ENERGY",
        "notes": "Swedish company developing vertical axis floating wind turbine technology.",
    },
    {
        "name": "Setana Town",
        "code": "SETANA_TOWN",
        "type": "GOVT",
        "notes": "Japanese municipality involved in local renewable energy development.",
    },
    {
        "name": "SFE Produksjon",
        "code": "SFE_PRODUKSJON",
        "type": "UTILITY",
        "notes": "Norwegian power production company focusing on renewable energy.",
    },
    {
        "name": "Shell",
        "code": "SHELL",
        "type": "ENERGY",
        "notes": "Global energy company with growing offshore wind portfolio including floating wind projects.",
    },
    {
        "name": "Siemens",
        "code": "SIEMENS",
        "type": "CORP",
        "notes": "German conglomerate, major wind turbine manufacturer through Siemens Gamesa Renewable Energy.",
    },
    {
        "name": "Siemens Financial Services",
        "code": "SIEMENS_FIN_SVCS",
        "type": "FIN_SVCS",
        "notes": "Financial arm of Siemens providing equity and debt financing for renewable energy projects.",
    },
    {
        "name": "SK E&S",
        "code": "SK_ENS",
        "type": "ENERGY",
        "notes": "South Korean energy company, part of SK Group, developing renewable energy projects including offshore wind.",
    },
    {
        "name": "Skyborn Renewables",
        "code": "SKYBORN_REN",
        "type": "DEVELOPER",
        "notes": "German offshore wind developer with projects across Europe, Asia-Pacific and Americas.",
    },
    {
        "name": "Socofe",
        "code": "SOCOFE",
        "type": "CORP",
        "notes": "Belgian holding company with energy infrastructure investments.",
    },
    {
        "name": "Solvind Prosjekt",
        "code": "SOLVIND_PROSJEKT",
        "type": "DEVELOPER",
        "notes": "Norwegian renewable energy project developer.",
    },
    {
        "name": "SRIW Group",
        "code": "SRIW_GROUP",
        "type": "GOVT",
        "notes": "Walloon regional investment company supporting renewable energy development in Belgium.",
    },
    {
        "name": "SSE",
        "code": "SSE",
        "type": "UTILITY",
        "notes": "Scottish and Southern Energy - UK utility company with major renewable energy portfolio including offshore wind.",
    },
    {
        "name": "Stadtwerke Lübeck",
        "code": "STADTWERKE_LUBECK",
        "type": "UTILITY",
        "notes": "German municipal utility investing in renewable energy projects for local supply.",
    },
    {
        "name": "Stadtwerke München",
        "code": "STADTWERKE_MUNCHEN",
        "type": "UTILITY",
        "notes": "Munich municipal utility with significant renewable energy investments including offshore wind.",
    },
    {
        "name": "Starwind Offshore consortium",
        "code": "STARWIND_OFFSHORE_CONSORTIUM",
        "type": "CONSORTIUM",
        "notes": "Consortium developing offshore wind projects.",
    },
    {
        "name": "Statkraft",
        "code": "STATKRAFT",
        "type": "UTILITY",
        "notes": "Norwegian state-owned company, Europe's largest renewable energy producer with hydro, wind and solar assets.",
    },
    {
        "name": "Stepstone",
        "code": "STEPSTONE",
        "type": "PE",
        "notes": "Global private markets investment firm with infrastructure funds investing in renewable energy.",
    },
    {
        "name": "Stiesdal",
        "code": "STIESDAL",
        "type": "CORP",
        "notes": "Danish company founded by wind pioneer Henrik Stiesdal, developing floating wind foundation technology.",
    },
    {
        "name": "Stonepeak",
        "code": "STONEPEAK",
        "type": "INFRA_FUND",
        "notes": "US infrastructure investment firm with significant renewable energy portfolio.",
    },
    {
        "name": "Sumitomo",
        "code": "SUMITOMO",
        "type": "CORP",
        "notes": "Japanese conglomerate with renewable energy investments including offshore wind projects globally.",
    },
    {
        "name": "Suomen Hyötytuuli",
        "code": "SUOMEN_HYOTYTUULI",
        "type": "DEVELOPER",
        "notes": "Finnish wind power developer, now part of OX2, developing projects across Nordic region.",
    },
    {
        "name": "SUSI Partners",
        "code": "SUSI_PRTNRS",
        "type": "ASSET_MGMT",
        "notes": "Swiss sustainable infrastructure fund manager focusing on energy transition investments.",
    },
    {
        "name": "SwifterwinT",
        "code": "SWIFTERWINT",
        "type": "DEVELOPER",
        "notes": "Dutch wind energy developer and operator.",
    },
    {
        "name": "Swiss Life Asset Managers",
        "code": "SWISS_LIFE_ASSET",
        "type": "ASSET_MGMT",
        "notes": "Asset management arm of Swiss Life Group investing in renewable energy infrastructure.",
    },
    {
        "name": "Synera Renewable Energy",
        "code": "SYNERA_REN_ENERGY",
        "type": "DEVELOPER",
        "notes": "Renewable energy project developer and operator.",
    },
    {
        "name": "Taaleri Energia Funds Management",
        "code": "TAALERI_ENERGY_FUNDS",
        "type": "ASSET_MGMT",
        "notes": "Finnish renewable energy fund manager with wind and solar investments across Europe and US.",
    },
    {
        "name": "Taipower",
        "code": "TAIPOWER",
        "type": "UTILITY",
        "notes": "Taiwan Power Company - State-owned electric utility developing offshore wind to meet renewable targets.",
    },
    {
        "name": "Taiwan Life Insurance",
        "code": "TAIWAN_LIFE_INSURANCE",
        "type": "INSURANCE",
        "notes": "Taiwanese insurance company investing in domestic renewable energy infrastructure.",
    },
    {
        "name": "Tenaga Nasional Berhad (TNB)",
        "code": "TNB",
        "type": "UTILITY",
        "notes": "Malaysian national electric utility expanding renewable energy portfolio across Southeast Asia.",
    },
    {
        "name": "Tension Technology International (TTI)",
        "code": "TTI",
        "type": "CORP",
        "notes": "Company specializing in tension leg platform technology for floating offshore structures.",
    },
    {
        "name": "TEPCO",
        "code": "TEPCO",
        "type": "UTILITY",
        "notes": "Tokyo Electric Power Company - Japanese utility developing offshore wind projects as part of decarbonization strategy.",
    },
    {
        "name": "Thai Electricity Generation Public Company (EGCO Group)",
        "code": "EGCO_GROUP",
        "type": "ENERGY",
        "notes": "Thai independent power producer with renewable energy projects across Asia-Pacific region.",
    },
    {
        "name": "Thyborøn-Harboøre",
        "code": "THYBORON_HARBOORE",
        "type": "COOP",
        "notes": "Danish wind energy cooperative in western Jutland.",
    },
    {
        "name": "TODA",
        "code": "TODA",
        "type": "CORP",
        "notes": "Japanese construction company involved in offshore wind infrastructure development.",
    },
    {
        "name": "Toho Gas",
        "code": "TOHO_GAS",
        "type": "UTILITY",
        "notes": "Japanese gas utility investing in renewable energy for diversification.",
    },
    {
        "name": "Tohoku Electric",
        "code": "TOHOKU_ELEC",
        "type": "UTILITY",
        "notes": "Japanese regional electric utility developing renewable energy including offshore wind projects.",
    },
    {
        "name": "Tokyo Gas",
        "code": "TOKYO_GAS",
        "type": "UTILITY",
        "notes": "Japan's largest gas utility expanding into renewable energy including offshore wind investments.",
    },
    {
        "name": "TotalEnergies",
        "code": "TOTALENERGIES",
        "type": "ENERGY",
        "notes": "French energy major with ambitious renewable targets, developing large-scale offshore wind projects globally.",
    },
    {
        "name": "Transglobe Life Insurance",
        "code": "TRANSGLOBE_LIFE_INSURANCE",
        "type": "INSURANCE",
        "notes": "Taiwanese life insurance company investing in renewable energy infrastructure.",
    },
    {
        "name": "Trianel",
        "code": "TRIANEL",
        "type": "UTILITY",
        "notes": "German municipal utility cooperation developing renewable energy projects including offshore wind.",
    },
    {
        "name": "TRIG",
        "code": "TRIG",
        "type": "INFRA_FUND",
        "notes": "The Renewables Infrastructure Group - London-listed renewable energy infrastructure investment company.",
    },
    {
        "name": "Troms Kraft Produksjon",
        "code": "TROMS_KRAFT_PRODUKSJON",
        "type": "UTILITY",
        "notes": "Norwegian regional power producer focusing on renewable energy in northern Norway.",
    },
    {
        "name": "TrønderEnergi Kraft",
        "code": "TRONDERENERGI_KRAFT",
        "type": "UTILITY",
        "notes": "Norwegian regional energy company producing hydroelectric and wind power.",
    },
    {
        "name": "UNITECH (Aker Solutions)",
        "code": "UNITECH_AKER_SOLUTIONS",
        "type": "CORP",
        "notes": "Part of Aker Solutions providing engineering services for offshore renewable energy projects.",
    },
    {
        "name": "Universities Superannuation Scheme",
        "code": "UNIVERSITIES_SUPERANNUATION_SCHEME",
        "type": "PENSION",
        "notes": "UK's largest private pension scheme investing in renewable energy infrastructure.",
    },
    {
        "name": "University of Maine",
        "code": "UNIVERSITY_OF_MAINE",
        "type": "RESEARCH",
        "notes": "US university leading floating offshore wind research with VolturnUS concrete hull technology.",
    },
    {
        "name": "University of Stuttgart",
        "code": "UNIVERSITY_OF_STUTTGART",
        "type": "RESEARCH",
        "notes": "German university conducting wind energy research including turbine design and grid integration.",
    },
    {
        "name": "University of Tokyo",
        "code": "UNIVERSITY_OF_TOKYO",
        "type": "RESEARCH",
        "notes": "Leading Japanese university researching offshore wind technology and marine renewable energy.",
    },
    {
        "name": "Unknown",
        "code": "UNKNOWN",
        "type": "UNKNOWN",
        "notes": "Owner information not available or undisclosed.",
    },
    {
        "name": "Vår Energi",
        "code": "VAR_ENERGY",
        "type": "ENERGY",
        "notes": "Norwegian oil and gas company (Eni/HitecVision JV) exploring offshore wind opportunities.",
    },
    {
        "name": "Varanger Kraft",
        "code": "VARANGER_KRAFT",
        "type": "UTILITY",
        "notes": "Norwegian regional utility developing renewable energy in Finnmark region including wind power.",
    },
    {
        "name": "Vardar",
        "code": "VARDAR",
        "type": "UTILITY",
        "notes": "Norwegian regional energy company owned by Buskerud County, investing in renewable energy.",
    },
    {
        "name": "Vårgrønn",
        "code": "VARGRONN",
        "type": "DEVELOPER",
        "notes": "Norwegian offshore wind developer, joint venture between Plenitude (Eni) and HitecVision.",
    },
    {
        "name": "Various",
        "code": "VARIOUS",
        "type": "UNKNOWN",
        "notes": "Multiple owners or consortium of various parties.",
    },
    {
        "name": "Vattenfall",
        "code": "VATTENFALL",
        "type": "UTILITY",
        "notes": "Swedish state-owned power company, major developer of offshore wind projects across Northern Europe.",
    },
    {
        "name": "Vauban Infrastructure Partners",
        "code": "VAUBAN_INFRA_PRTNRS",
        "type": "INFRA_FUND",
        "notes": "European infrastructure fund manager investing in renewable energy and energy transition assets.",
    },
    {
        "name": "Vendée Energie",
        "code": "VENDEE_ENERGY",
        "type": "UTILITY",
        "notes": "French regional energy company developing renewable projects in Vendée department.",
    },
    {
        "name": "Venti",
        "code": "VENTI",
        "type": "DEVELOPER",
        "notes": "Renewable energy developer specializing in wind power projects.",
    },
    {
        "name": "Vindenergi",
        "code": "VINDENERGI",
        "type": "DEVELOPER",
        "notes": "Wind energy developer and operator.",
    },
    {
        "name": "Westermeerwind",
        "code": "WESTERMEERWIND",
        "type": "DEVELOPER",
        "notes": "Dutch nearshore wind farm developer and operator in IJsselmeer.",
    },
    {
        "name": "Wind Power Group",
        "code": "WIND_PWR_GROUP",
        "type": "DEVELOPER",
        "notes": "Wind power development company with projects in multiple markets.",
    },
    {
        "name": "Windland Energieerzeugungs",
        "code": "WINDLAND_ENERGIEERZEUGUNGS",
        "type": "DEVELOPER",
        "notes": "German wind energy generation company.",
    },
    {
        "name": "Windpark Fryslân",
        "code": "WINDPARK_FRYSLAN",
        "type": "DEVELOPER",
        "notes": "Developer of nearshore wind farm in Dutch IJsselmeer lake.",
    },
    {
        "name": "X1 Wind",
        "code": "X1_WIND",
        "type": "ENERGY",
        "notes": "Spanish company developing innovative floating wind platform with single-point mooring system.",
    },
    {
        "name": "Zeewind",
        "code": "ZEEWIND",
        "type": "DEVELOPER",
        "notes": "Dutch offshore wind developer and operator.",
    },
    {
        "name": "Z-Kracht",
        "code": "Z_KRACHT",
        "type": "DEVELOPER",
        "notes": "Dutch renewable energy developer focusing on wind power projects.",
    },
    {
        "name": "Gravis Capital",
        "code": "GRAVIS_CAP",
        "type": "ASSET_MGMT",
        "notes": "UK investment manager specializing in infrastructure including renewable energy funds.",
    },
    {
        "name": "GreenPower",
        "code": "GREENPWR",
        "type": "DEVELOPER",
        "notes": "Renewable energy developer focusing on green power generation projects.",
    },
    {
        "name": "Gresham House Wind Energy",
        "code": "GRESHAM_HOUSE_WIND",
        "type": "ASSET_MGMT",
        "notes": "UK specialist alternative asset manager with dedicated wind energy funds.",
    },
    {
        "name": "Hermes Infrastructure",
        "code": "HERMES_INFRA",
        "type": "INFRA_FUND",
        "notes": "Infrastructure investment manager focusing on essential assets including renewable energy.",
    },
    {
        "name": "Independent investors",
        "code": "INDEPENDENT_INVESTORS",
        "type": "UNKNOWN",
        "notes": "Various independent or private investors not otherwise categorized.",
    },
    {
        "name": "Landowner or private owner",
        "code": "LANDOWNER_OR_PRIVATE",
        "type": "UNKNOWN",
        "notes": "Individual landowners or private entities owning renewable energy assets.",
    },
    {
        "name": "Logie Estate",
        "code": "LOGIE_ESTATE",
        "type": "UNKNOWN",
        "notes": "Scottish estate with renewable energy developments on its land.",
    },
    {
        "name": "Muirden Energy",
        "code": "MUIRDEN_ENERGY",
        "type": "DEVELOPER",
        "notes": "UK renewable energy developer focusing on wind and solar projects.",
    },
    {
        "name": "NTR",
        "code": "NTR",
        "type": "DEVELOPER",
        "notes": "Irish renewable energy developer and asset manager with wind and solar projects across Europe.",
    },
    {
        "name": "Octopus Group",
        "code": "OCTOPUS_GROUP",
        "type": "PE",
        "notes": "UK investment company with major renewable energy portfolio through various funds and vehicles.",
    },
    {
        "name": "Octopus Renewables Infrastructure SCSp",
        "code": "OCTOPUS_REN_INFRA",
        "type": "INFRA_FUND",
        "notes": "Luxembourg-based renewable infrastructure fund managed by Octopus.",
    },
    {
        "name": "Octopus Renewables Infrastructure Trust",
        "code": "OCTOPUS_REN_INFRA_2",
        "type": "INFRA_FUND",
        "notes": "London-listed renewable energy infrastructure investment trust managed by Octopus.",
    },
    {
        "name": "OnPath Energy",
        "code": "ONPATH_ENERGY",
        "type": "DEVELOPER",
        "notes": "Renewable energy developer and operator.",
    },
    {
        "name": "Red Rock Renewables",
        "code": "RED_ROCK_REN",
        "type": "DEVELOPER",
        "notes": "UK renewable energy developer specializing in wind and solar projects.",
    },
    {
        "name": "Rockbysea",
        "code": "ROCKBYSEA",
        "type": "DEVELOPER",
        "notes": "Renewable energy developer focusing on coastal and offshore projects.",
    },
    {
        "name": "RPMI Railpen",
        "code": "RPMI_RAILPEN",
        "type": "PENSION",
        "notes": "UK railway pension scheme investing in renewable energy infrastructure.",
    },
    {
        "name": "ScottishPower Renewables (Iberdrola)",
        "code": "SCOTTISHPWR_REN_IBERDROLA",
        "type": "UTILITY",
        "notes": "UK subsidiary of Iberdrola, major developer of onshore and offshore wind projects in UK.",
    },
    {
        "name": "Temporis Capital",
        "code": "TEMPORIS_CAP",
        "type": "PE",
        "notes": "Private equity firm with renewable energy infrastructure investments.",
    },
    {
        "name": "UK Renewables Energy Group",
        "code": "UK_REN_ENERGY",
        "type": "DEVELOPER",
        "notes": "UK-based renewable energy development company.",
    },
    {
        "name": "Vantage RE",
        "code": "VANTAGE_RE",
        "type": "DEVELOPER",
        "notes": "Renewable energy developer and asset manager.",
    },
]


def seed_owners(db: Session):
    """Seed owners table with initial data"""
    print(f"  Checking for existing owners...")
    # Get existing owner codes
    existing_codes = {o.code for o in db.query(Owner.code).all()}

    # Filter out owners that already exist and map types
    owners_to_add = []
    for owner_data in OWNERS_DATA:
        if owner_data["code"] not in existing_codes:
            # Create a copy and map the type to schema-allowed value
            mapped_data = owner_data.copy()
            mapped_data["type"] = map_owner_type(owner_data["type"])
            owners_to_add.append(Owner(**mapped_data))

    if not owners_to_add:
        print(f"  Found {len(existing_codes)} existing owners, no new owners to add")
        return

    print(f"  Adding {len(owners_to_add)} new owners...")
    db.add_all(owners_to_add)
    db.commit()
    print(f"  Successfully added {len(owners_to_add)} owners")

    # Print summary by mapped type
    mapped_type_counts = {}
    for owner_data in OWNERS_DATA:
        mapped_type = map_owner_type(owner_data["type"])
        mapped_type_counts[mapped_type] = mapped_type_counts.get(mapped_type, 0) + 1

    print(f"  Owner distribution by mapped type:")
    for owner_type, count in sorted(mapped_type_counts.items()):
        print(f"    {owner_type}: {count}")

    # Also show original type distribution
    original_type_counts = {}
    for owner_data in OWNERS_DATA:
        original_type = owner_data["type"]
        original_type_counts[original_type] = original_type_counts.get(original_type, 0) + 1

    print(f"  Original type distribution:")
    for owner_type, count in sorted(original_type_counts.items()):
        mapped_type = map_owner_type(owner_type)
        print(f"    {owner_type} -> {mapped_type}: {count}")
