"""SCADA finding-lifecycle model — the human-worked state of a Predict finding.

Phase 7b. The SCADA opportunity register (``scada.opportunity_register``, owned and regenerated by
energyexe-scada-pipeline) is read-only detection output; its ``id`` is a volatile per-farm ordinal
the pipeline truncates+reloads on every persist. This table records the *human* lifecycle a
superadmin applies to a finding — acknowledge / confirm / dismiss / resolve, plus a note and
who-acted — and must therefore key on the **stable natural key** ``(farm, trigger, scope, cls)``,
never the register ``id``.

It is app-authored state written only by the API (never by the pipeline), so it lives in the ordinary
public schema as a normal core model — same shape as ``DataAnomaly`` (String status + Python-layer
enum, ``updated_by`` FK to ``users.id``) — not in the ``scada`` schema. The read side
(``ScadaOpportunityService``) LEFT-joins it onto the register rows by the natural key.
"""

from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


def _utcnow() -> datetime:
    """Naive-UTC, the house idiom for new timestamp columns (see the opportunities model)."""
    return datetime.now(timezone.utc).replace(tzinfo=None)


class ScadaFindingAction(Base):
    """The current lifecycle state of one SCADA finding (one row per natural key)."""

    __tablename__ = "scada_finding_action"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)

    # Stable natural key of the finding (mirrors scada.opportunity_register columns). ``trigger`` is
    # normalised to '' (never NULL) so the unique key and the read-join match — the register's
    # ``trigger`` is COALESCE(...,'')-d on the join side.
    farm: Mapped[str] = mapped_column(String(64), nullable=False)
    trigger: Mapped[str] = mapped_column(String(48), nullable=False, server_default="")
    scope: Mapped[str] = mapped_column(String(32), nullable=False)
    cls: Mapped[str] = mapped_column(String(16), nullable=False)

    # Lifecycle. Status is a plain string validated in Python (house convention — no DB enum/CHECK).
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="ACKNOWLEDGED")
    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Attribution — who last acted + the resolution milestones.
    acknowledged_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    resolved_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    updated_by: Mapped[Optional[int]] = mapped_column(
        Integer, ForeignKey("users.id"), nullable=True
    )

    created_at: Mapped[datetime] = mapped_column(DateTime, default=_utcnow, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=_utcnow, onupdate=_utcnow, nullable=False
    )

    updater = relationship("User", foreign_keys=[updated_by])

    __table_args__ = (
        UniqueConstraint("farm", "trigger", "scope", "cls", name="uq_scada_finding_action_key"),
    )

    def __repr__(self) -> str:
        return (
            f"<ScadaFindingAction(farm='{self.farm}', trigger='{self.trigger}', "
            f"scope='{self.scope}', cls='{self.cls}', status='{self.status}')>"
        )


class ScadaFindingStatus:
    """Lifecycle statuses (D-013). ``NEW`` is the implicit absence of a row — never stored."""

    NEW = "NEW"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    CONFIRMED = "CONFIRMED"
    DISMISSED = "DISMISSED"
    RESOLVED = "RESOLVED"


# The transitions the API accepts as a target status (NEW is implicit-only).
SCADA_FINDING_WRITABLE_STATUSES = frozenset(
    {
        ScadaFindingStatus.ACKNOWLEDGED,
        ScadaFindingStatus.CONFIRMED,
        ScadaFindingStatus.DISMISSED,
        ScadaFindingStatus.RESOLVED,
    }
)
