"""Periodic Digest PDF renderer (EPR-87).

Scorecard-style sections render as tables with the delta spelled out in text
("96.5 (+9.5%)") — the standard PDF fonts have no arrow glyphs, and a signed
percentage is clearer on paper anyway.
"""

from datetime import datetime, timezone
from pathlib import Path

from app.models.report import Report, SectionStatus
from app.services.reports.pdf.builder import PdfBuilder
from app.services.reports.pdf.charts import generation_comparison_chart


def _section(report: Report, key: str):
    for s in report.sections:
        if s.section_key == key:
            return s
    return None


def _cell(row: dict, col_key: str) -> str:
    value = row["values"].get(col_key, "n/a")
    if value == "n/a":
        return "n/a"
    unit = row.get("unit")
    text = f"{value} {unit}".strip() if unit else value
    if col_key != "current":
        delta = (row.get("delta_pct") or {}).get(col_key)
        if delta is not None:
            text += f"  ({delta:+.1f}%)"
    return text


def _scorecard_table(pdf: PdfBuilder, data: dict) -> None:
    columns = data.get("columns", [])
    rows = data.get("rows", [])
    if not columns or not rows:
        return
    header = ["Metric"] + [c["label"] for c in columns]
    body = []
    for row in rows:
        label = row["label"] + (f" ({row['unit']})" if row.get("unit") else "")
        body.append([label] + [_cell(row, c["key"]) for c in columns])
    pdf.table(header, body)
    for note in data.get("notes", []):
        pdf.small(note)


def render(report: Report, tmp_dir: Path) -> Path:
    scope_name = report.windfarm.name if report.windfarm is not None else report.title
    subtitle = (
        f"Periodic digest · {report.period_start:%d %b %Y} – {report.period_end:%d %b %Y}"
        f" · generated {datetime.now(timezone.utc):%d %b %Y} · v{report.version}"
    )
    pdf = PdfBuilder(f"{scope_name} — Periodic Digest", subtitle=subtitle)

    exec_summary = _section(report, "executive_summary")
    if exec_summary is not None and (exec_summary.narrative_json or exec_summary.narrative_text):
        pdf.heading("Executive Summary")
        summary = exec_summary.narrative_json or {}
        if summary.get("bullets"):
            if summary.get("overall_assessment"):
                pdf.paragraph(summary["overall_assessment"])
            pdf.bullets([b.get("text", "") for b in summary["bullets"]])
        elif exec_summary.narrative_text:
            for para in exec_summary.narrative_text.split("\n\n"):
                if para.strip():
                    pdf.paragraph(para.strip())

    scorecard = _section(report, "scorecard")
    if scorecard is not None and scorecard.status == SectionStatus.GENERATED and scorecard.data:
        pdf.heading("Period Scorecard")
        _scorecard_table(pdf, scorecard.data)

    chart = _section(report, "generation_chart")
    if chart is not None and chart.status == SectionStatus.GENERATED and chart.data:
        series = chart.data.get("series") or {}
        if (series.get("current") or {}).get("points"):
            pdf.heading("Generation")
            chart_path = generation_comparison_chart(series, tmp_dir / "generation.png")
            pdf.image(chart_path, width_in=6.0)

    findings = _section(report, "finding_changes")
    if findings is not None and findings.status == SectionStatus.GENERATED and findings.data:
        pdf.heading("Finding Changes")
        if findings.data.get("rows"):
            _scorecard_table(pdf, findings.data)
        else:
            for note in findings.data.get("notes", []):
                pdf.small(note)

    resource = _section(report, "wind_resource")
    if resource is not None and resource.status == SectionStatus.GENERATED and resource.data:
        pdf.heading("Wind Resource")
        pdf.metric_cards(resource.data.get("cards", []))
        if resource.data.get("note"):
            pdf.small(resource.data["note"])

    pdf.small(
        "Generated by the EnergyExe platform. All comparisons are against the "
        "previous period and, where shown, the same period last year."
    )

    out = tmp_dir / "report.pdf"
    pdf.save(out)
    return out
