"""Opportunity Report PDF renderer (EPR-88)."""

from datetime import datetime, timezone
from pathlib import Path

from app.models.report import Report, SectionStatus
from app.services.reports.pdf.builder import MUTED, SEVERITY_COLORS, PdfBuilder
from app.services.reports.pdf.charts import severity_bar_chart


def _section(report: Report, key: str):
    for s in report.sections:
        if s.section_key == key:
            return s
    return None


def render(report: Report, tmp_dir: Path) -> Path:
    scope_name = report.windfarm.name if report.windfarm is not None else report.title
    subtitle = (
        f"Opportunity assessment · {report.period_start:%d %b %Y} – {report.period_end:%d %b %Y}"
        f" · generated {datetime.now(timezone.utc):%d %b %Y} · v{report.version}"
    )
    pdf = PdfBuilder(f"{scope_name} — Opportunity Report", subtitle=subtitle)

    exec_summary = _section(report, "executive_summary")
    if exec_summary is not None and (exec_summary.narrative_json or exec_summary.narrative_text):
        pdf.heading("Executive Summary")
        summary = exec_summary.narrative_json or {}
        if summary.get("bullets"):
            if summary.get("overall_assessment"):
                pdf.paragraph(summary["overall_assessment"])
            pdf.bullets([b.get("text", "") for b in summary["bullets"]])
        elif exec_summary.narrative_text:
            for para in exec_summary.narrative_text.split("\n\n"):
                if para.strip():
                    pdf.paragraph(para.strip())

    metrics = _section(report, "key_metrics")
    if metrics is not None and metrics.status == SectionStatus.GENERATED and metrics.data:
        pdf.heading("Key Metrics")
        pdf.metric_cards(metrics.data.get("cards", []))

    findings = _section(report, "findings")
    if findings is not None and findings.status == SectionStatus.GENERATED and findings.data:
        pdf.heading("Performance Snapshot")
        counts = findings.data.get("severity_counts", {})
        chart_path = severity_bar_chart(counts, tmp_dir / "severity.png")
        pdf.image(chart_path, width_in=5.6)

        rows = findings.data.get("rows", [])
        body = []
        row_colors = []
        for r in rows:
            severity = (r.get("severity") or "").lower()
            body.append(
                [
                    r.get("domain", ""),
                    r.get("display_name", ""),
                    r.get("schema_code", ""),
                    r.get("key_metric") or "—",
                    severity.capitalize(),
                ]
            )
            row_colors.append(MUTED if severity == "pass" else SEVERITY_COLORS.get(severity))
        pdf.table(
            ["Domain", "Finding", "Schema", "Key metric", "Severity"],
            body,
            row_text_colors=row_colors,
        )

        suppressed = [r for r in rows if (r.get("severity") or "").lower() == "suppressed"]
        for r in suppressed:
            if r.get("suppression_reason"):
                pdf.small(f"{r['schema_code']} suppressed: {r['suppression_reason']}")

    action_plan = _section(report, "action_plan")
    if action_plan is not None and (action_plan.narrative_json or action_plan.narrative_text):
        pdf.heading("Action Plan")
        tiers = (action_plan.narrative_json or {}).get("tiers")
        if tiers:
            for tier in tiers:
                pdf.heading(f"{tier.get('tier', '')} — {tier.get('label', '')}", level=3)
                items = []
                for action in tier.get("actions", []):
                    tags = " · ".join(
                        t
                        for t in (
                            action.get("horizon"),
                            action.get("external"),
                            ", ".join(action.get("linked_schemas") or []) or None,
                        )
                        if t
                    )
                    items.append(action.get("title", "") + (f"  ({tags})" if tags else ""))
                if items:
                    pdf.bullets(items)
                if tier.get("context"):
                    pdf.small(tier["context"])
        elif action_plan.narrative_text:
            for para in action_plan.narrative_text.split("\n\n"):
                if para.strip():
                    pdf.paragraph(para.strip())

    pdf.small(
        "Generated by the EnergyExe platform. Findings reflect the detection engine's "
        "current assessment; metrics are computed over the stated period."
    )

    out = tmp_dir / "report.pdf"
    pdf.save(out)
    return out
